/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.operations.async;

import static com.prove.proveapi.operations.Operations.AsyncRequestOperation;

import com.prove.proveapi.SDKConfiguration;
import com.prove.proveapi.models.components.V3EnrollIdentityRequest;
import com.prove.proveapi.operations.V3EnrollIdentity;
import com.prove.proveapi.utils.Headers;
import com.prove.proveapi.utils.Utils;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class V3EnrollIdentityRequestBuilder {

    private Optional<? extends V3EnrollIdentityRequest> request = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public V3EnrollIdentityRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public V3EnrollIdentityRequestBuilder request(V3EnrollIdentityRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public V3EnrollIdentityRequestBuilder request(Optional<? extends V3EnrollIdentityRequest> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<V3EnrollIdentityResponse> call() {
        
        AsyncRequestOperation<Optional<? extends V3EnrollIdentityRequest>, V3EnrollIdentityResponse> operation
              = new V3EnrollIdentity.Async(sdkConfiguration, _headers);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
