/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.operations.async;

import static com.prove.proveapi.operations.Operations.AsyncRequestOperation;

import com.prove.proveapi.SDKConfiguration;
import com.prove.proveapi.models.operations.V3GetIdentitiesByPhoneNumberRequest;
import com.prove.proveapi.operations.V3GetIdentitiesByPhoneNumber;
import com.prove.proveapi.utils.Headers;
import com.prove.proveapi.utils.Utils;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class V3GetIdentitiesByPhoneNumberRequestBuilder {

    private String mobileNumber;
    private Optional<String> clientRequestId = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public V3GetIdentitiesByPhoneNumberRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public V3GetIdentitiesByPhoneNumberRequestBuilder mobileNumber(String mobileNumber) {
        Utils.checkNotNull(mobileNumber, "mobileNumber");
        this.mobileNumber = mobileNumber;
        return this;
    }
                
    public V3GetIdentitiesByPhoneNumberRequestBuilder clientRequestId(String clientRequestId) {
        Utils.checkNotNull(clientRequestId, "clientRequestId");
        this.clientRequestId = Optional.of(clientRequestId);
        return this;
    }

    public V3GetIdentitiesByPhoneNumberRequestBuilder clientRequestId(Optional<String> clientRequestId) {
        Utils.checkNotNull(clientRequestId, "clientRequestId");
        this.clientRequestId = clientRequestId;
        return this;
    }


    private V3GetIdentitiesByPhoneNumberRequest buildRequest() {

        V3GetIdentitiesByPhoneNumberRequest request = new V3GetIdentitiesByPhoneNumberRequest(mobileNumber,
            clientRequestId);

        return request;
    }

    public CompletableFuture<V3GetIdentitiesByPhoneNumberResponse> call() {
        
        AsyncRequestOperation<V3GetIdentitiesByPhoneNumberRequest, V3GetIdentitiesByPhoneNumberResponse> operation
              = new V3GetIdentitiesByPhoneNumber.Async(sdkConfiguration, _headers);
        V3GetIdentitiesByPhoneNumberRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
