/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.prove.proveapi.utils.AsyncResponse;
import com.prove.proveapi.utils.Blob;
import com.prove.proveapi.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class V3GetIdentitiesByPhoneNumberResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * V3GetIdentitiesByPhoneNumberResponse
     */
    private Optional<? extends com.prove.proveapi.models.components.V3GetIdentitiesByPhoneNumberResponse> v3GetIdentitiesByPhoneNumberResponse;

    @JsonCreator
    public V3GetIdentitiesByPhoneNumberResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse,
            Optional<? extends com.prove.proveapi.models.components.V3GetIdentitiesByPhoneNumberResponse> v3GetIdentitiesByPhoneNumberResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(v3GetIdentitiesByPhoneNumberResponse, "v3GetIdentitiesByPhoneNumberResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.v3GetIdentitiesByPhoneNumberResponse = v3GetIdentitiesByPhoneNumberResponse;
    }
    
    public V3GetIdentitiesByPhoneNumberResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<Blob> rawResponse() {
        return rawResponse;
    }

    /**
     * V3GetIdentitiesByPhoneNumberResponse
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<com.prove.proveapi.models.components.V3GetIdentitiesByPhoneNumberResponse> v3GetIdentitiesByPhoneNumberResponse() {
        return (Optional<com.prove.proveapi.models.components.V3GetIdentitiesByPhoneNumberResponse>) v3GetIdentitiesByPhoneNumberResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public V3GetIdentitiesByPhoneNumberResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public V3GetIdentitiesByPhoneNumberResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public V3GetIdentitiesByPhoneNumberResponse withRawResponse(HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * V3GetIdentitiesByPhoneNumberResponse
     */
    public V3GetIdentitiesByPhoneNumberResponse withV3GetIdentitiesByPhoneNumberResponse(com.prove.proveapi.models.components.V3GetIdentitiesByPhoneNumberResponse v3GetIdentitiesByPhoneNumberResponse) {
        Utils.checkNotNull(v3GetIdentitiesByPhoneNumberResponse, "v3GetIdentitiesByPhoneNumberResponse");
        this.v3GetIdentitiesByPhoneNumberResponse = Optional.ofNullable(v3GetIdentitiesByPhoneNumberResponse);
        return this;
    }


    /**
     * V3GetIdentitiesByPhoneNumberResponse
     */
    public V3GetIdentitiesByPhoneNumberResponse withV3GetIdentitiesByPhoneNumberResponse(Optional<? extends com.prove.proveapi.models.components.V3GetIdentitiesByPhoneNumberResponse> v3GetIdentitiesByPhoneNumberResponse) {
        Utils.checkNotNull(v3GetIdentitiesByPhoneNumberResponse, "v3GetIdentitiesByPhoneNumberResponse");
        this.v3GetIdentitiesByPhoneNumberResponse = v3GetIdentitiesByPhoneNumberResponse;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3GetIdentitiesByPhoneNumberResponse other = (V3GetIdentitiesByPhoneNumberResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.v3GetIdentitiesByPhoneNumberResponse, other.v3GetIdentitiesByPhoneNumberResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            v3GetIdentitiesByPhoneNumberResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3GetIdentitiesByPhoneNumberResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "v3GetIdentitiesByPhoneNumberResponse", v3GetIdentitiesByPhoneNumberResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<Blob> rawResponse;

        private Optional<? extends com.prove.proveapi.models.components.V3GetIdentitiesByPhoneNumberResponse> v3GetIdentitiesByPhoneNumberResponse = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<Blob> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * V3GetIdentitiesByPhoneNumberResponse
         */
        public Builder v3GetIdentitiesByPhoneNumberResponse(com.prove.proveapi.models.components.V3GetIdentitiesByPhoneNumberResponse v3GetIdentitiesByPhoneNumberResponse) {
            Utils.checkNotNull(v3GetIdentitiesByPhoneNumberResponse, "v3GetIdentitiesByPhoneNumberResponse");
            this.v3GetIdentitiesByPhoneNumberResponse = Optional.ofNullable(v3GetIdentitiesByPhoneNumberResponse);
            return this;
        }

        /**
         * V3GetIdentitiesByPhoneNumberResponse
         */
        public Builder v3GetIdentitiesByPhoneNumberResponse(Optional<? extends com.prove.proveapi.models.components.V3GetIdentitiesByPhoneNumberResponse> v3GetIdentitiesByPhoneNumberResponse) {
            Utils.checkNotNull(v3GetIdentitiesByPhoneNumberResponse, "v3GetIdentitiesByPhoneNumberResponse");
            this.v3GetIdentitiesByPhoneNumberResponse = v3GetIdentitiesByPhoneNumberResponse;
            return this;
        }

        public V3GetIdentitiesByPhoneNumberResponse build() {

            return new V3GetIdentitiesByPhoneNumberResponse(
                contentType, statusCode, rawResponse,
                v3GetIdentitiesByPhoneNumberResponse);
        }

    }
}
