/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.operations.async;

import static com.prove.proveapi.operations.Operations.AsyncRequestOperation;

import com.prove.proveapi.SDKConfiguration;
import com.prove.proveapi.models.components.V3UnifyBindRequest;
import com.prove.proveapi.utils.Headers;
import com.prove.proveapi.utils.Utils;
import java.lang.Exception;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class V3UnifyBindRequestRequestBuilder {

    private Optional<? extends V3UnifyBindRequest> request = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public V3UnifyBindRequestRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public V3UnifyBindRequestRequestBuilder request(V3UnifyBindRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public V3UnifyBindRequestRequestBuilder request(Optional<? extends V3UnifyBindRequest> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<V3UnifyBindRequestResponse> call() throws Exception {
        
        AsyncRequestOperation<Optional<? extends V3UnifyBindRequest>, V3UnifyBindRequestResponse> operation
              = new com.prove.proveapi.operations.V3UnifyBindRequest.Async(sdkConfiguration, _headers);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
