/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.operations;

import static com.prove.proveapi.operations.Operations.RequestOperation;

import com.prove.proveapi.SDKConfiguration;
import com.prove.proveapi.models.components.V3CompleteRequest;
import com.prove.proveapi.utils.Headers;
import com.prove.proveapi.utils.Utils;
import java.lang.Exception;
import java.util.Optional;

public class V3CompleteRequestRequestBuilder {

    private Optional<? extends V3CompleteRequest> request = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public V3CompleteRequestRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public V3CompleteRequestRequestBuilder request(V3CompleteRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public V3CompleteRequestRequestBuilder request(Optional<? extends V3CompleteRequest> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public V3CompleteRequestResponse call() throws Exception {
        
        RequestOperation<Optional<? extends V3CompleteRequest>, V3CompleteRequestResponse> operation
              = new com.prove.proveapi.operations.V3CompleteRequest.Sync(sdkConfiguration, _headers);

        return operation.handleResponse(operation.doRequest(request));
    }
}
