/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.prove.proveapi.utils.Response;
import com.prove.proveapi.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class V3CrossDomainIdentityResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * V3CrossDomainIdentityResponse
     */
    private Optional<? extends com.prove.proveapi.models.components.V3CrossDomainIdentityResponse> v3CrossDomainIdentityResponse;

    @JsonCreator
    public V3CrossDomainIdentityResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends com.prove.proveapi.models.components.V3CrossDomainIdentityResponse> v3CrossDomainIdentityResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(v3CrossDomainIdentityResponse, "v3CrossDomainIdentityResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.v3CrossDomainIdentityResponse = v3CrossDomainIdentityResponse;
    }
    
    public V3CrossDomainIdentityResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * V3CrossDomainIdentityResponse
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<com.prove.proveapi.models.components.V3CrossDomainIdentityResponse> v3CrossDomainIdentityResponse() {
        return (Optional<com.prove.proveapi.models.components.V3CrossDomainIdentityResponse>) v3CrossDomainIdentityResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public V3CrossDomainIdentityResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public V3CrossDomainIdentityResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public V3CrossDomainIdentityResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * V3CrossDomainIdentityResponse
     */
    public V3CrossDomainIdentityResponse withV3CrossDomainIdentityResponse(com.prove.proveapi.models.components.V3CrossDomainIdentityResponse v3CrossDomainIdentityResponse) {
        Utils.checkNotNull(v3CrossDomainIdentityResponse, "v3CrossDomainIdentityResponse");
        this.v3CrossDomainIdentityResponse = Optional.ofNullable(v3CrossDomainIdentityResponse);
        return this;
    }


    /**
     * V3CrossDomainIdentityResponse
     */
    public V3CrossDomainIdentityResponse withV3CrossDomainIdentityResponse(Optional<? extends com.prove.proveapi.models.components.V3CrossDomainIdentityResponse> v3CrossDomainIdentityResponse) {
        Utils.checkNotNull(v3CrossDomainIdentityResponse, "v3CrossDomainIdentityResponse");
        this.v3CrossDomainIdentityResponse = v3CrossDomainIdentityResponse;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3CrossDomainIdentityResponse other = (V3CrossDomainIdentityResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.v3CrossDomainIdentityResponse, other.v3CrossDomainIdentityResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            v3CrossDomainIdentityResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3CrossDomainIdentityResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "v3CrossDomainIdentityResponse", v3CrossDomainIdentityResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<InputStream> rawResponse;

        private Optional<? extends com.prove.proveapi.models.components.V3CrossDomainIdentityResponse> v3CrossDomainIdentityResponse = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * V3CrossDomainIdentityResponse
         */
        public Builder v3CrossDomainIdentityResponse(com.prove.proveapi.models.components.V3CrossDomainIdentityResponse v3CrossDomainIdentityResponse) {
            Utils.checkNotNull(v3CrossDomainIdentityResponse, "v3CrossDomainIdentityResponse");
            this.v3CrossDomainIdentityResponse = Optional.ofNullable(v3CrossDomainIdentityResponse);
            return this;
        }

        /**
         * V3CrossDomainIdentityResponse
         */
        public Builder v3CrossDomainIdentityResponse(Optional<? extends com.prove.proveapi.models.components.V3CrossDomainIdentityResponse> v3CrossDomainIdentityResponse) {
            Utils.checkNotNull(v3CrossDomainIdentityResponse, "v3CrossDomainIdentityResponse");
            this.v3CrossDomainIdentityResponse = v3CrossDomainIdentityResponse;
            return this;
        }

        public V3CrossDomainIdentityResponse build() {

            return new V3CrossDomainIdentityResponse(
                contentType, statusCode, rawResponse,
                v3CrossDomainIdentityResponse);
        }

    }
}
