/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.operations;

import com.prove.proveapi.models.components.V3IdentityDeactivateRequest;
import com.prove.proveapi.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;

public class V3DeactivateIdentityRequestBuilder {

    private String identityId;
    private Optional<? extends V3IdentityDeactivateRequest> v3IdentityDeactivateRequest = Optional.empty();
    private final SDKMethodInterfaces.MethodCallV3DeactivateIdentity sdk;

    public V3DeactivateIdentityRequestBuilder(SDKMethodInterfaces.MethodCallV3DeactivateIdentity sdk) {
        this.sdk = sdk;
    }

    public V3DeactivateIdentityRequestBuilder identityId(String identityId) {
        Utils.checkNotNull(identityId, "identityId");
        this.identityId = identityId;
        return this;
    }
                
    public V3DeactivateIdentityRequestBuilder v3IdentityDeactivateRequest(V3IdentityDeactivateRequest v3IdentityDeactivateRequest) {
        Utils.checkNotNull(v3IdentityDeactivateRequest, "v3IdentityDeactivateRequest");
        this.v3IdentityDeactivateRequest = Optional.of(v3IdentityDeactivateRequest);
        return this;
    }

    public V3DeactivateIdentityRequestBuilder v3IdentityDeactivateRequest(Optional<? extends V3IdentityDeactivateRequest> v3IdentityDeactivateRequest) {
        Utils.checkNotNull(v3IdentityDeactivateRequest, "v3IdentityDeactivateRequest");
        this.v3IdentityDeactivateRequest = v3IdentityDeactivateRequest;
        return this;
    }

    public V3DeactivateIdentityResponse call() throws Exception {

        return sdk.v3DeactivateIdentity(
            identityId,
            v3IdentityDeactivateRequest);
    }
}
