/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.operations;

import static com.prove.proveapi.operations.Operations.RequestOperation;

import com.prove.proveapi.SDKConfiguration;
import com.prove.proveapi.models.components.V3IdentityDeactivateRequest;
import com.prove.proveapi.operations.V3DeactivateIdentity;
import com.prove.proveapi.utils.Headers;
import com.prove.proveapi.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class V3DeactivateIdentityRequestBuilder {

    private String identityId;
    private Optional<? extends V3IdentityDeactivateRequest> v3IdentityDeactivateRequest = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public V3DeactivateIdentityRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public V3DeactivateIdentityRequestBuilder identityId(String identityId) {
        Utils.checkNotNull(identityId, "identityId");
        this.identityId = identityId;
        return this;
    }
                
    public V3DeactivateIdentityRequestBuilder v3IdentityDeactivateRequest(V3IdentityDeactivateRequest v3IdentityDeactivateRequest) {
        Utils.checkNotNull(v3IdentityDeactivateRequest, "v3IdentityDeactivateRequest");
        this.v3IdentityDeactivateRequest = Optional.of(v3IdentityDeactivateRequest);
        return this;
    }

    public V3DeactivateIdentityRequestBuilder v3IdentityDeactivateRequest(Optional<? extends V3IdentityDeactivateRequest> v3IdentityDeactivateRequest) {
        Utils.checkNotNull(v3IdentityDeactivateRequest, "v3IdentityDeactivateRequest");
        this.v3IdentityDeactivateRequest = v3IdentityDeactivateRequest;
        return this;
    }


    private V3DeactivateIdentityRequest buildRequest() {

        V3DeactivateIdentityRequest request = new V3DeactivateIdentityRequest(identityId,
            v3IdentityDeactivateRequest);

        return request;
    }

    public V3DeactivateIdentityResponse call() {
        
        RequestOperation<V3DeactivateIdentityRequest, V3DeactivateIdentityResponse> operation
              = new V3DeactivateIdentity.Sync(sdkConfiguration, _headers);
        V3DeactivateIdentityRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
