/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.prove.proveapi.utils.SpeakeasyMetadata;
import com.prove.proveapi.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class V3DisenrollIdentityRequest {
    /**
     * A Prove-generated unique ID for a specific identity.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=identityId")
    private String identityId;

    /**
     * A client-generated unique ID for a specific session. This can be used to identify specific requests.
     * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
     * be accepted.
     * 
     * <p>Do not include Personally Identifiable Information (PII) in this field.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=clientRequestId")
    private Optional<String> clientRequestId;

    @JsonCreator
    public V3DisenrollIdentityRequest(
            String identityId,
            Optional<String> clientRequestId) {
        Utils.checkNotNull(identityId, "identityId");
        Utils.checkNotNull(clientRequestId, "clientRequestId");
        this.identityId = identityId;
        this.clientRequestId = clientRequestId;
    }
    
    public V3DisenrollIdentityRequest(
            String identityId) {
        this(identityId, Optional.empty());
    }

    /**
     * A Prove-generated unique ID for a specific identity.
     */
    @JsonIgnore
    public String identityId() {
        return identityId;
    }

    /**
     * A client-generated unique ID for a specific session. This can be used to identify specific requests.
     * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
     * be accepted.
     * 
     * <p>Do not include Personally Identifiable Information (PII) in this field.
     */
    @JsonIgnore
    public Optional<String> clientRequestId() {
        return clientRequestId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A Prove-generated unique ID for a specific identity.
     */
    public V3DisenrollIdentityRequest withIdentityId(String identityId) {
        Utils.checkNotNull(identityId, "identityId");
        this.identityId = identityId;
        return this;
    }

    /**
     * A client-generated unique ID for a specific session. This can be used to identify specific requests.
     * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
     * be accepted.
     * 
     * <p>Do not include Personally Identifiable Information (PII) in this field.
     */
    public V3DisenrollIdentityRequest withClientRequestId(String clientRequestId) {
        Utils.checkNotNull(clientRequestId, "clientRequestId");
        this.clientRequestId = Optional.ofNullable(clientRequestId);
        return this;
    }


    /**
     * A client-generated unique ID for a specific session. This can be used to identify specific requests.
     * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
     * be accepted.
     * 
     * <p>Do not include Personally Identifiable Information (PII) in this field.
     */
    public V3DisenrollIdentityRequest withClientRequestId(Optional<String> clientRequestId) {
        Utils.checkNotNull(clientRequestId, "clientRequestId");
        this.clientRequestId = clientRequestId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3DisenrollIdentityRequest other = (V3DisenrollIdentityRequest) o;
        return 
            Utils.enhancedDeepEquals(this.identityId, other.identityId) &&
            Utils.enhancedDeepEquals(this.clientRequestId, other.clientRequestId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            identityId, clientRequestId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3DisenrollIdentityRequest.class,
                "identityId", identityId,
                "clientRequestId", clientRequestId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String identityId;

        private Optional<String> clientRequestId = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * A Prove-generated unique ID for a specific identity.
         */
        public Builder identityId(String identityId) {
            Utils.checkNotNull(identityId, "identityId");
            this.identityId = identityId;
            return this;
        }


        /**
         * A client-generated unique ID for a specific session. This can be used to identify specific requests.
         * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
         * be accepted.
         * 
         * <p>Do not include Personally Identifiable Information (PII) in this field.
         */
        public Builder clientRequestId(String clientRequestId) {
            Utils.checkNotNull(clientRequestId, "clientRequestId");
            this.clientRequestId = Optional.ofNullable(clientRequestId);
            return this;
        }

        /**
         * A client-generated unique ID for a specific session. This can be used to identify specific requests.
         * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
         * be accepted.
         * 
         * <p>Do not include Personally Identifiable Information (PII) in this field.
         */
        public Builder clientRequestId(Optional<String> clientRequestId) {
            Utils.checkNotNull(clientRequestId, "clientRequestId");
            this.clientRequestId = clientRequestId;
            return this;
        }

        public V3DisenrollIdentityRequest build() {

            return new V3DisenrollIdentityRequest(
                identityId, clientRequestId);
        }

    }
}
