/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.prove.proveapi.utils.SpeakeasyMetadata;
import com.prove.proveapi.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class V3DiscoverRequestRequest {
    /**
     * A unique Prove-generated identifier for the enrolled identity (UUID).
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=proveId")
    private String proveId;

    /**
     * A client-generated unique ID for a specific session. This can be used to identify specific requests.
     * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
     * be accepted.
     * 
     * <p>Do not include Personally Identifiable Information (PII) in this field.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=clientRequestId")
    private Optional<String> clientRequestId;

    @JsonCreator
    public V3DiscoverRequestRequest(
            String proveId,
            Optional<String> clientRequestId) {
        Utils.checkNotNull(proveId, "proveId");
        Utils.checkNotNull(clientRequestId, "clientRequestId");
        this.proveId = proveId;
        this.clientRequestId = clientRequestId;
    }
    
    public V3DiscoverRequestRequest(
            String proveId) {
        this(proveId, Optional.empty());
    }

    /**
     * A unique Prove-generated identifier for the enrolled identity (UUID).
     */
    @JsonIgnore
    public String proveId() {
        return proveId;
    }

    /**
     * A client-generated unique ID for a specific session. This can be used to identify specific requests.
     * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
     * be accepted.
     * 
     * <p>Do not include Personally Identifiable Information (PII) in this field.
     */
    @JsonIgnore
    public Optional<String> clientRequestId() {
        return clientRequestId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A unique Prove-generated identifier for the enrolled identity (UUID).
     */
    public V3DiscoverRequestRequest withProveId(String proveId) {
        Utils.checkNotNull(proveId, "proveId");
        this.proveId = proveId;
        return this;
    }

    /**
     * A client-generated unique ID for a specific session. This can be used to identify specific requests.
     * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
     * be accepted.
     * 
     * <p>Do not include Personally Identifiable Information (PII) in this field.
     */
    public V3DiscoverRequestRequest withClientRequestId(String clientRequestId) {
        Utils.checkNotNull(clientRequestId, "clientRequestId");
        this.clientRequestId = Optional.ofNullable(clientRequestId);
        return this;
    }


    /**
     * A client-generated unique ID for a specific session. This can be used to identify specific requests.
     * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
     * be accepted.
     * 
     * <p>Do not include Personally Identifiable Information (PII) in this field.
     */
    public V3DiscoverRequestRequest withClientRequestId(Optional<String> clientRequestId) {
        Utils.checkNotNull(clientRequestId, "clientRequestId");
        this.clientRequestId = clientRequestId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3DiscoverRequestRequest other = (V3DiscoverRequestRequest) o;
        return 
            Utils.enhancedDeepEquals(this.proveId, other.proveId) &&
            Utils.enhancedDeepEquals(this.clientRequestId, other.clientRequestId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            proveId, clientRequestId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3DiscoverRequestRequest.class,
                "proveId", proveId,
                "clientRequestId", clientRequestId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String proveId;

        private Optional<String> clientRequestId = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * A unique Prove-generated identifier for the enrolled identity (UUID).
         */
        public Builder proveId(String proveId) {
            Utils.checkNotNull(proveId, "proveId");
            this.proveId = proveId;
            return this;
        }


        /**
         * A client-generated unique ID for a specific session. This can be used to identify specific requests.
         * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
         * be accepted.
         * 
         * <p>Do not include Personally Identifiable Information (PII) in this field.
         */
        public Builder clientRequestId(String clientRequestId) {
            Utils.checkNotNull(clientRequestId, "clientRequestId");
            this.clientRequestId = Optional.ofNullable(clientRequestId);
            return this;
        }

        /**
         * A client-generated unique ID for a specific session. This can be used to identify specific requests.
         * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
         * be accepted.
         * 
         * <p>Do not include Personally Identifiable Information (PII) in this field.
         */
        public Builder clientRequestId(Optional<String> clientRequestId) {
            Utils.checkNotNull(clientRequestId, "clientRequestId");
            this.clientRequestId = clientRequestId;
            return this;
        }

        public V3DiscoverRequestRequest build() {

            return new V3DiscoverRequestRequest(
                proveId, clientRequestId);
        }

    }
}
