/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.operations;

import static com.prove.proveapi.operations.Operations.RequestOperation;

import com.prove.proveapi.SDKConfiguration;
import com.prove.proveapi.operations.V3DomainID;
import com.prove.proveapi.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;

public class V3DomainIDRequestBuilder {

    private Optional<String> request = Optional.empty();
    private final SDKConfiguration sdkConfiguration;

    public V3DomainIDRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public V3DomainIDRequestBuilder request(String request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public V3DomainIDRequestBuilder request(Optional<String> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public V3DomainIDResponse call() throws Exception {
        
        RequestOperation<Optional<String>, V3DomainIDResponse> operation
              = new V3DomainID.Sync(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
