/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.operations;

import static com.prove.proveapi.operations.Operations.RequestOperation;

import com.prove.proveapi.SDKConfiguration;
import com.prove.proveapi.models.components.V3DomainConfirmLinkRequest;
import com.prove.proveapi.utils.Utils;
import java.lang.Exception;
import java.util.Optional;

public class V3DomainConfirmLinkRequestRequestBuilder {

    private Optional<? extends V3DomainConfirmLinkRequest> request = Optional.empty();
    private final SDKConfiguration sdkConfiguration;

    public V3DomainConfirmLinkRequestRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public V3DomainConfirmLinkRequestRequestBuilder request(V3DomainConfirmLinkRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public V3DomainConfirmLinkRequestRequestBuilder request(Optional<? extends V3DomainConfirmLinkRequest> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public V3DomainConfirmLinkRequestResponse call() throws Exception {
        
        RequestOperation<Optional<? extends V3DomainConfirmLinkRequest>, V3DomainConfirmLinkRequestResponse> operation
              = new com.prove.proveapi.operations.V3DomainConfirmLinkRequest.Sync(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
