/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.prove.proveapi.utils.Response;
import com.prove.proveapi.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;

public class V3EnrollIdentityResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * V3EnrollIdentityResponse
     */
    private Optional<? extends com.prove.proveapi.models.components.V3EnrollIdentityResponse> v3EnrollIdentityResponse;

    @JsonCreator
    public V3EnrollIdentityResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends com.prove.proveapi.models.components.V3EnrollIdentityResponse> v3EnrollIdentityResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(v3EnrollIdentityResponse, "v3EnrollIdentityResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.v3EnrollIdentityResponse = v3EnrollIdentityResponse;
    }
    
    public V3EnrollIdentityResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * V3EnrollIdentityResponse
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<com.prove.proveapi.models.components.V3EnrollIdentityResponse> v3EnrollIdentityResponse() {
        return (Optional<com.prove.proveapi.models.components.V3EnrollIdentityResponse>) v3EnrollIdentityResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * HTTP response content type for this operation
     */
    public V3EnrollIdentityResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public V3EnrollIdentityResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public V3EnrollIdentityResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * V3EnrollIdentityResponse
     */
    public V3EnrollIdentityResponse withV3EnrollIdentityResponse(com.prove.proveapi.models.components.V3EnrollIdentityResponse v3EnrollIdentityResponse) {
        Utils.checkNotNull(v3EnrollIdentityResponse, "v3EnrollIdentityResponse");
        this.v3EnrollIdentityResponse = Optional.ofNullable(v3EnrollIdentityResponse);
        return this;
    }

    /**
     * V3EnrollIdentityResponse
     */
    public V3EnrollIdentityResponse withV3EnrollIdentityResponse(Optional<? extends com.prove.proveapi.models.components.V3EnrollIdentityResponse> v3EnrollIdentityResponse) {
        Utils.checkNotNull(v3EnrollIdentityResponse, "v3EnrollIdentityResponse");
        this.v3EnrollIdentityResponse = v3EnrollIdentityResponse;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3EnrollIdentityResponse other = (V3EnrollIdentityResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.v3EnrollIdentityResponse, other.v3EnrollIdentityResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            v3EnrollIdentityResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3EnrollIdentityResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "v3EnrollIdentityResponse", v3EnrollIdentityResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends com.prove.proveapi.models.components.V3EnrollIdentityResponse> v3EnrollIdentityResponse = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * V3EnrollIdentityResponse
         */
        public Builder v3EnrollIdentityResponse(com.prove.proveapi.models.components.V3EnrollIdentityResponse v3EnrollIdentityResponse) {
            Utils.checkNotNull(v3EnrollIdentityResponse, "v3EnrollIdentityResponse");
            this.v3EnrollIdentityResponse = Optional.ofNullable(v3EnrollIdentityResponse);
            return this;
        }

        /**
         * V3EnrollIdentityResponse
         */
        public Builder v3EnrollIdentityResponse(Optional<? extends com.prove.proveapi.models.components.V3EnrollIdentityResponse> v3EnrollIdentityResponse) {
            Utils.checkNotNull(v3EnrollIdentityResponse, "v3EnrollIdentityResponse");
            this.v3EnrollIdentityResponse = v3EnrollIdentityResponse;
            return this;
        }
        
        public V3EnrollIdentityResponse build() {
            return new V3EnrollIdentityResponse(
                contentType,
                statusCode,
                rawResponse,
                v3EnrollIdentityResponse);
        }
    }
}
