/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.operations;

import com.prove.proveapi.models.components.V3UnifyBindRequest;
import com.prove.proveapi.utils.Utils;
import java.lang.Exception;
import java.util.Optional;

public class V3UnifyBindRequestRequestBuilder {

    private Optional<? extends V3UnifyBindRequest> request = Optional.empty();
    private final SDKMethodInterfaces.MethodCallV3UnifyBindRequest sdk;

    public V3UnifyBindRequestRequestBuilder(SDKMethodInterfaces.MethodCallV3UnifyBindRequest sdk) {
        this.sdk = sdk;
    }
                
    public V3UnifyBindRequestRequestBuilder request(V3UnifyBindRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public V3UnifyBindRequestRequestBuilder request(Optional<? extends V3UnifyBindRequest> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public V3UnifyBindRequestResponse call() throws Exception {

        return sdk.v3UnifyBindRequest(
            request);
    }
}
