/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.operations;

import static com.prove.proveapi.operations.Operations.RequestOperation;

import com.prove.proveapi.SDKConfiguration;
import com.prove.proveapi.models.components.V3VerifyBatchRequest;
import com.prove.proveapi.utils.Headers;
import com.prove.proveapi.utils.Utils;
import java.util.Optional;

public class V3VerifyBatchRequestRequestBuilder {

    private Optional<? extends V3VerifyBatchRequest> request = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public V3VerifyBatchRequestRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public V3VerifyBatchRequestRequestBuilder request(V3VerifyBatchRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public V3VerifyBatchRequestRequestBuilder request(Optional<? extends V3VerifyBatchRequest> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public V3VerifyBatchRequestResponse call() {
        
        RequestOperation<Optional<? extends V3VerifyBatchRequest>, V3VerifyBatchRequestResponse> operation
              = new com.prove.proveapi.operations.V3VerifyBatchRequest.Sync(sdkConfiguration, _headers);

        return operation.handleResponse(operation.doRequest(request));
    }
}
