/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.prove.proveapi.proveapi;

import com.prove.proveapi.proveapi.utils.Hook.SdkInitData;
import com.prove.proveapi.proveapi.utils.HTTPClient;
import com.prove.proveapi.proveapi.utils.RetryConfig;
import com.prove.proveapi.proveapi.models.components.Security;
import java.util.Optional;

class SDKConfiguration {
    public SecuritySource securitySource;
    
    public Optional<SecuritySource> securitySource() {
        return Optional.ofNullable(securitySource);
    }
    public HTTPClient defaultClient;
      public String serverUrl;
    public int serverIdx = 0;
    public String language = "java";
    public String openapiDocVersion = "1.0.0";
    public String sdkVersion = "0.0.1";
    public String genVersion = "2.333.3";
    public String userAgent = "speakeasy-sdk/java 0.0.1 2.333.3 1.0.0 com.prove.proveapi.proveapi";

    private com.prove.proveapi.proveapi.utils.Hooks _hooks = new com.prove.proveapi.proveapi.utils.Hooks();

    public com.prove.proveapi.proveapi.utils.Hooks hooks() {
        return _hooks;
    }

    public void setHooks(com.prove.proveapi.proveapi.utils.Hooks hooks) {
        this._hooks = hooks;
    }

    /** 
     * Initializes state (for example hooks).
     **/
    public void initialize() {
        com.prove.proveapi.proveapi.hooks.SDKHooks.initialize(_hooks);
        // apply the sdk init hook immediately
        SdkInitData data = _hooks.sdkInit(new SdkInitData(serverUrl, defaultClient));
        this.serverUrl = data.baseUrl();
        this.defaultClient = data.client();
    }

    
    
    public Optional<RetryConfig> retryConfig = Optional.empty();
}
