/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.prove.proveapi.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class AuthContinueResponseSubjectMobileResult {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("error")
    private Optional<? extends AuthContinueResponseError> error;

    /**
     * Success will be true if the bind was successful.
     */
    @JsonProperty("success")
    private boolean success;

    @JsonCreator
    public AuthContinueResponseSubjectMobileResult(
            @JsonProperty("error") Optional<? extends AuthContinueResponseError> error,
            @JsonProperty("success") boolean success) {
        Utils.checkNotNull(error, "error");
        Utils.checkNotNull(success, "success");
        this.error = error;
        this.success = success;
    }
    
    public AuthContinueResponseSubjectMobileResult(
            boolean success) {
        this(Optional.empty(), success);
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AuthContinueResponseError> error() {
        return (Optional<AuthContinueResponseError>) error;
    }

    /**
     * Success will be true if the bind was successful.
     */
    @JsonIgnore
    public boolean success() {
        return success;
    }

    public static Builder builder() {
        return new Builder();
    }


    public AuthContinueResponseSubjectMobileResult withError(AuthContinueResponseError error) {
        Utils.checkNotNull(error, "error");
        this.error = Optional.ofNullable(error);
        return this;
    }


    public AuthContinueResponseSubjectMobileResult withError(Optional<? extends AuthContinueResponseError> error) {
        Utils.checkNotNull(error, "error");
        this.error = error;
        return this;
    }

    /**
     * Success will be true if the bind was successful.
     */
    public AuthContinueResponseSubjectMobileResult withSuccess(boolean success) {
        Utils.checkNotNull(success, "success");
        this.success = success;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthContinueResponseSubjectMobileResult other = (AuthContinueResponseSubjectMobileResult) o;
        return 
            Utils.enhancedDeepEquals(this.error, other.error) &&
            Utils.enhancedDeepEquals(this.success, other.success);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            error, success);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AuthContinueResponseSubjectMobileResult.class,
                "error", error,
                "success", success);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends AuthContinueResponseError> error = Optional.empty();

        private Boolean success;

        private Builder() {
          // force use of static builder() method
        }


        public Builder error(AuthContinueResponseError error) {
            Utils.checkNotNull(error, "error");
            this.error = Optional.ofNullable(error);
            return this;
        }

        public Builder error(Optional<? extends AuthContinueResponseError> error) {
            Utils.checkNotNull(error, "error");
            this.error = error;
            return this;
        }


        /**
         * Success will be true if the bind was successful.
         */
        public Builder success(boolean success) {
            Utils.checkNotNull(success, "success");
            this.success = success;
            return this;
        }

        public AuthContinueResponseSubjectMobileResult build() {

            return new AuthContinueResponseSubjectMobileResult(
                error, success);
        }

    }
}
