/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.prove.proveapi.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class AuthStartRequestDeliveryScanNotification {
    /**
     * Body is the body of the scan QR message.
     */
    @JsonProperty("body")
    private String body;

    /**
     * ConfirmButton is the text of the scan QR message confirm button.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("confirmBtn")
    private Optional<String> confirmBtn;

    /**
     * DenyButton is the text of the scan QR message deny button.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("denyBtn")
    private Optional<String> denyBtn;

    /**
     * OriginatingDevice is the type of device where where the scan QR flow was initiated.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("originatingDevice")
    private Optional<String> originatingDevice;

    /**
     * OriginatingIp is the IP address of the web client where the scan QR flow was initiated.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("originatingIp")
    private Optional<String> originatingIp;

    /**
     * Title is the title of the scan QR message.
     */
    @JsonProperty("title")
    private String title;

    @JsonCreator
    public AuthStartRequestDeliveryScanNotification(
            @JsonProperty("body") String body,
            @JsonProperty("confirmBtn") Optional<String> confirmBtn,
            @JsonProperty("denyBtn") Optional<String> denyBtn,
            @JsonProperty("originatingDevice") Optional<String> originatingDevice,
            @JsonProperty("originatingIp") Optional<String> originatingIp,
            @JsonProperty("title") String title) {
        Utils.checkNotNull(body, "body");
        Utils.checkNotNull(confirmBtn, "confirmBtn");
        Utils.checkNotNull(denyBtn, "denyBtn");
        Utils.checkNotNull(originatingDevice, "originatingDevice");
        Utils.checkNotNull(originatingIp, "originatingIp");
        Utils.checkNotNull(title, "title");
        this.body = body;
        this.confirmBtn = confirmBtn;
        this.denyBtn = denyBtn;
        this.originatingDevice = originatingDevice;
        this.originatingIp = originatingIp;
        this.title = title;
    }
    
    public AuthStartRequestDeliveryScanNotification(
            String body,
            String title) {
        this(body, Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), title);
    }

    /**
     * Body is the body of the scan QR message.
     */
    @JsonIgnore
    public String body() {
        return body;
    }

    /**
     * ConfirmButton is the text of the scan QR message confirm button.
     */
    @JsonIgnore
    public Optional<String> confirmBtn() {
        return confirmBtn;
    }

    /**
     * DenyButton is the text of the scan QR message deny button.
     */
    @JsonIgnore
    public Optional<String> denyBtn() {
        return denyBtn;
    }

    /**
     * OriginatingDevice is the type of device where where the scan QR flow was initiated.
     */
    @JsonIgnore
    public Optional<String> originatingDevice() {
        return originatingDevice;
    }

    /**
     * OriginatingIp is the IP address of the web client where the scan QR flow was initiated.
     */
    @JsonIgnore
    public Optional<String> originatingIp() {
        return originatingIp;
    }

    /**
     * Title is the title of the scan QR message.
     */
    @JsonIgnore
    public String title() {
        return title;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Body is the body of the scan QR message.
     */
    public AuthStartRequestDeliveryScanNotification withBody(String body) {
        Utils.checkNotNull(body, "body");
        this.body = body;
        return this;
    }

    /**
     * ConfirmButton is the text of the scan QR message confirm button.
     */
    public AuthStartRequestDeliveryScanNotification withConfirmBtn(String confirmBtn) {
        Utils.checkNotNull(confirmBtn, "confirmBtn");
        this.confirmBtn = Optional.ofNullable(confirmBtn);
        return this;
    }


    /**
     * ConfirmButton is the text of the scan QR message confirm button.
     */
    public AuthStartRequestDeliveryScanNotification withConfirmBtn(Optional<String> confirmBtn) {
        Utils.checkNotNull(confirmBtn, "confirmBtn");
        this.confirmBtn = confirmBtn;
        return this;
    }

    /**
     * DenyButton is the text of the scan QR message deny button.
     */
    public AuthStartRequestDeliveryScanNotification withDenyBtn(String denyBtn) {
        Utils.checkNotNull(denyBtn, "denyBtn");
        this.denyBtn = Optional.ofNullable(denyBtn);
        return this;
    }


    /**
     * DenyButton is the text of the scan QR message deny button.
     */
    public AuthStartRequestDeliveryScanNotification withDenyBtn(Optional<String> denyBtn) {
        Utils.checkNotNull(denyBtn, "denyBtn");
        this.denyBtn = denyBtn;
        return this;
    }

    /**
     * OriginatingDevice is the type of device where where the scan QR flow was initiated.
     */
    public AuthStartRequestDeliveryScanNotification withOriginatingDevice(String originatingDevice) {
        Utils.checkNotNull(originatingDevice, "originatingDevice");
        this.originatingDevice = Optional.ofNullable(originatingDevice);
        return this;
    }


    /**
     * OriginatingDevice is the type of device where where the scan QR flow was initiated.
     */
    public AuthStartRequestDeliveryScanNotification withOriginatingDevice(Optional<String> originatingDevice) {
        Utils.checkNotNull(originatingDevice, "originatingDevice");
        this.originatingDevice = originatingDevice;
        return this;
    }

    /**
     * OriginatingIp is the IP address of the web client where the scan QR flow was initiated.
     */
    public AuthStartRequestDeliveryScanNotification withOriginatingIp(String originatingIp) {
        Utils.checkNotNull(originatingIp, "originatingIp");
        this.originatingIp = Optional.ofNullable(originatingIp);
        return this;
    }


    /**
     * OriginatingIp is the IP address of the web client where the scan QR flow was initiated.
     */
    public AuthStartRequestDeliveryScanNotification withOriginatingIp(Optional<String> originatingIp) {
        Utils.checkNotNull(originatingIp, "originatingIp");
        this.originatingIp = originatingIp;
        return this;
    }

    /**
     * Title is the title of the scan QR message.
     */
    public AuthStartRequestDeliveryScanNotification withTitle(String title) {
        Utils.checkNotNull(title, "title");
        this.title = title;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthStartRequestDeliveryScanNotification other = (AuthStartRequestDeliveryScanNotification) o;
        return 
            Utils.enhancedDeepEquals(this.body, other.body) &&
            Utils.enhancedDeepEquals(this.confirmBtn, other.confirmBtn) &&
            Utils.enhancedDeepEquals(this.denyBtn, other.denyBtn) &&
            Utils.enhancedDeepEquals(this.originatingDevice, other.originatingDevice) &&
            Utils.enhancedDeepEquals(this.originatingIp, other.originatingIp) &&
            Utils.enhancedDeepEquals(this.title, other.title);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            body, confirmBtn, denyBtn,
            originatingDevice, originatingIp, title);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AuthStartRequestDeliveryScanNotification.class,
                "body", body,
                "confirmBtn", confirmBtn,
                "denyBtn", denyBtn,
                "originatingDevice", originatingDevice,
                "originatingIp", originatingIp,
                "title", title);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String body;

        private Optional<String> confirmBtn = Optional.empty();

        private Optional<String> denyBtn = Optional.empty();

        private Optional<String> originatingDevice = Optional.empty();

        private Optional<String> originatingIp = Optional.empty();

        private String title;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Body is the body of the scan QR message.
         */
        public Builder body(String body) {
            Utils.checkNotNull(body, "body");
            this.body = body;
            return this;
        }


        /**
         * ConfirmButton is the text of the scan QR message confirm button.
         */
        public Builder confirmBtn(String confirmBtn) {
            Utils.checkNotNull(confirmBtn, "confirmBtn");
            this.confirmBtn = Optional.ofNullable(confirmBtn);
            return this;
        }

        /**
         * ConfirmButton is the text of the scan QR message confirm button.
         */
        public Builder confirmBtn(Optional<String> confirmBtn) {
            Utils.checkNotNull(confirmBtn, "confirmBtn");
            this.confirmBtn = confirmBtn;
            return this;
        }


        /**
         * DenyButton is the text of the scan QR message deny button.
         */
        public Builder denyBtn(String denyBtn) {
            Utils.checkNotNull(denyBtn, "denyBtn");
            this.denyBtn = Optional.ofNullable(denyBtn);
            return this;
        }

        /**
         * DenyButton is the text of the scan QR message deny button.
         */
        public Builder denyBtn(Optional<String> denyBtn) {
            Utils.checkNotNull(denyBtn, "denyBtn");
            this.denyBtn = denyBtn;
            return this;
        }


        /**
         * OriginatingDevice is the type of device where where the scan QR flow was initiated.
         */
        public Builder originatingDevice(String originatingDevice) {
            Utils.checkNotNull(originatingDevice, "originatingDevice");
            this.originatingDevice = Optional.ofNullable(originatingDevice);
            return this;
        }

        /**
         * OriginatingDevice is the type of device where where the scan QR flow was initiated.
         */
        public Builder originatingDevice(Optional<String> originatingDevice) {
            Utils.checkNotNull(originatingDevice, "originatingDevice");
            this.originatingDevice = originatingDevice;
            return this;
        }


        /**
         * OriginatingIp is the IP address of the web client where the scan QR flow was initiated.
         */
        public Builder originatingIp(String originatingIp) {
            Utils.checkNotNull(originatingIp, "originatingIp");
            this.originatingIp = Optional.ofNullable(originatingIp);
            return this;
        }

        /**
         * OriginatingIp is the IP address of the web client where the scan QR flow was initiated.
         */
        public Builder originatingIp(Optional<String> originatingIp) {
            Utils.checkNotNull(originatingIp, "originatingIp");
            this.originatingIp = originatingIp;
            return this;
        }


        /**
         * Title is the title of the scan QR message.
         */
        public Builder title(String title) {
            Utils.checkNotNull(title, "title");
            this.title = title;
            return this;
        }

        public AuthStartRequestDeliveryScanNotification build() {

            return new AuthStartRequestDeliveryScanNotification(
                body, confirmBtn, denyBtn,
                originatingDevice, originatingIp, title);
        }

    }
}
