/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.prove.proveapi.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class AuthStartRequestSubjectMobileAuthenticators {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("instant")
    private Optional<? extends AuthStartRequestSubjectMobileAuthenticatorInstant> instant;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("instantlink")
    private Optional<? extends AuthStartRequestSubjectMobileAuthenticatorInstantLink> instantlink;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("otp")
    private Optional<? extends AuthStartRequestSubjectMobileAuthenticatorOTP> otp;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("passive")
    private Optional<? extends AuthStartRequestSubjectMobileAuthenticatorPassive> passive;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("universal")
    private Optional<? extends AuthStartRequestSubjectMobileAuthenticatorUniversal> universal;

    @JsonCreator
    public AuthStartRequestSubjectMobileAuthenticators(
            @JsonProperty("instant") Optional<? extends AuthStartRequestSubjectMobileAuthenticatorInstant> instant,
            @JsonProperty("instantlink") Optional<? extends AuthStartRequestSubjectMobileAuthenticatorInstantLink> instantlink,
            @JsonProperty("otp") Optional<? extends AuthStartRequestSubjectMobileAuthenticatorOTP> otp,
            @JsonProperty("passive") Optional<? extends AuthStartRequestSubjectMobileAuthenticatorPassive> passive,
            @JsonProperty("universal") Optional<? extends AuthStartRequestSubjectMobileAuthenticatorUniversal> universal) {
        Utils.checkNotNull(instant, "instant");
        Utils.checkNotNull(instantlink, "instantlink");
        Utils.checkNotNull(otp, "otp");
        Utils.checkNotNull(passive, "passive");
        Utils.checkNotNull(universal, "universal");
        this.instant = instant;
        this.instantlink = instantlink;
        this.otp = otp;
        this.passive = passive;
        this.universal = universal;
    }
    
    public AuthStartRequestSubjectMobileAuthenticators() {
        this(Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AuthStartRequestSubjectMobileAuthenticatorInstant> instant() {
        return (Optional<AuthStartRequestSubjectMobileAuthenticatorInstant>) instant;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AuthStartRequestSubjectMobileAuthenticatorInstantLink> instantlink() {
        return (Optional<AuthStartRequestSubjectMobileAuthenticatorInstantLink>) instantlink;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AuthStartRequestSubjectMobileAuthenticatorOTP> otp() {
        return (Optional<AuthStartRequestSubjectMobileAuthenticatorOTP>) otp;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AuthStartRequestSubjectMobileAuthenticatorPassive> passive() {
        return (Optional<AuthStartRequestSubjectMobileAuthenticatorPassive>) passive;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AuthStartRequestSubjectMobileAuthenticatorUniversal> universal() {
        return (Optional<AuthStartRequestSubjectMobileAuthenticatorUniversal>) universal;
    }

    public static Builder builder() {
        return new Builder();
    }


    public AuthStartRequestSubjectMobileAuthenticators withInstant(AuthStartRequestSubjectMobileAuthenticatorInstant instant) {
        Utils.checkNotNull(instant, "instant");
        this.instant = Optional.ofNullable(instant);
        return this;
    }


    public AuthStartRequestSubjectMobileAuthenticators withInstant(Optional<? extends AuthStartRequestSubjectMobileAuthenticatorInstant> instant) {
        Utils.checkNotNull(instant, "instant");
        this.instant = instant;
        return this;
    }

    public AuthStartRequestSubjectMobileAuthenticators withInstantlink(AuthStartRequestSubjectMobileAuthenticatorInstantLink instantlink) {
        Utils.checkNotNull(instantlink, "instantlink");
        this.instantlink = Optional.ofNullable(instantlink);
        return this;
    }


    public AuthStartRequestSubjectMobileAuthenticators withInstantlink(Optional<? extends AuthStartRequestSubjectMobileAuthenticatorInstantLink> instantlink) {
        Utils.checkNotNull(instantlink, "instantlink");
        this.instantlink = instantlink;
        return this;
    }

    public AuthStartRequestSubjectMobileAuthenticators withOtp(AuthStartRequestSubjectMobileAuthenticatorOTP otp) {
        Utils.checkNotNull(otp, "otp");
        this.otp = Optional.ofNullable(otp);
        return this;
    }


    public AuthStartRequestSubjectMobileAuthenticators withOtp(Optional<? extends AuthStartRequestSubjectMobileAuthenticatorOTP> otp) {
        Utils.checkNotNull(otp, "otp");
        this.otp = otp;
        return this;
    }

    public AuthStartRequestSubjectMobileAuthenticators withPassive(AuthStartRequestSubjectMobileAuthenticatorPassive passive) {
        Utils.checkNotNull(passive, "passive");
        this.passive = Optional.ofNullable(passive);
        return this;
    }


    public AuthStartRequestSubjectMobileAuthenticators withPassive(Optional<? extends AuthStartRequestSubjectMobileAuthenticatorPassive> passive) {
        Utils.checkNotNull(passive, "passive");
        this.passive = passive;
        return this;
    }

    public AuthStartRequestSubjectMobileAuthenticators withUniversal(AuthStartRequestSubjectMobileAuthenticatorUniversal universal) {
        Utils.checkNotNull(universal, "universal");
        this.universal = Optional.ofNullable(universal);
        return this;
    }


    public AuthStartRequestSubjectMobileAuthenticators withUniversal(Optional<? extends AuthStartRequestSubjectMobileAuthenticatorUniversal> universal) {
        Utils.checkNotNull(universal, "universal");
        this.universal = universal;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthStartRequestSubjectMobileAuthenticators other = (AuthStartRequestSubjectMobileAuthenticators) o;
        return 
            Utils.enhancedDeepEquals(this.instant, other.instant) &&
            Utils.enhancedDeepEquals(this.instantlink, other.instantlink) &&
            Utils.enhancedDeepEquals(this.otp, other.otp) &&
            Utils.enhancedDeepEquals(this.passive, other.passive) &&
            Utils.enhancedDeepEquals(this.universal, other.universal);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            instant, instantlink, otp,
            passive, universal);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AuthStartRequestSubjectMobileAuthenticators.class,
                "instant", instant,
                "instantlink", instantlink,
                "otp", otp,
                "passive", passive,
                "universal", universal);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends AuthStartRequestSubjectMobileAuthenticatorInstant> instant = Optional.empty();

        private Optional<? extends AuthStartRequestSubjectMobileAuthenticatorInstantLink> instantlink = Optional.empty();

        private Optional<? extends AuthStartRequestSubjectMobileAuthenticatorOTP> otp = Optional.empty();

        private Optional<? extends AuthStartRequestSubjectMobileAuthenticatorPassive> passive = Optional.empty();

        private Optional<? extends AuthStartRequestSubjectMobileAuthenticatorUniversal> universal = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder instant(AuthStartRequestSubjectMobileAuthenticatorInstant instant) {
            Utils.checkNotNull(instant, "instant");
            this.instant = Optional.ofNullable(instant);
            return this;
        }

        public Builder instant(Optional<? extends AuthStartRequestSubjectMobileAuthenticatorInstant> instant) {
            Utils.checkNotNull(instant, "instant");
            this.instant = instant;
            return this;
        }


        public Builder instantlink(AuthStartRequestSubjectMobileAuthenticatorInstantLink instantlink) {
            Utils.checkNotNull(instantlink, "instantlink");
            this.instantlink = Optional.ofNullable(instantlink);
            return this;
        }

        public Builder instantlink(Optional<? extends AuthStartRequestSubjectMobileAuthenticatorInstantLink> instantlink) {
            Utils.checkNotNull(instantlink, "instantlink");
            this.instantlink = instantlink;
            return this;
        }


        public Builder otp(AuthStartRequestSubjectMobileAuthenticatorOTP otp) {
            Utils.checkNotNull(otp, "otp");
            this.otp = Optional.ofNullable(otp);
            return this;
        }

        public Builder otp(Optional<? extends AuthStartRequestSubjectMobileAuthenticatorOTP> otp) {
            Utils.checkNotNull(otp, "otp");
            this.otp = otp;
            return this;
        }


        public Builder passive(AuthStartRequestSubjectMobileAuthenticatorPassive passive) {
            Utils.checkNotNull(passive, "passive");
            this.passive = Optional.ofNullable(passive);
            return this;
        }

        public Builder passive(Optional<? extends AuthStartRequestSubjectMobileAuthenticatorPassive> passive) {
            Utils.checkNotNull(passive, "passive");
            this.passive = passive;
            return this;
        }


        public Builder universal(AuthStartRequestSubjectMobileAuthenticatorUniversal universal) {
            Utils.checkNotNull(universal, "universal");
            this.universal = Optional.ofNullable(universal);
            return this;
        }

        public Builder universal(Optional<? extends AuthStartRequestSubjectMobileAuthenticatorUniversal> universal) {
            Utils.checkNotNull(universal, "universal");
            this.universal = universal;
            return this;
        }

        public AuthStartRequestSubjectMobileAuthenticators build() {

            return new AuthStartRequestSubjectMobileAuthenticators(
                instant, instantlink, otp,
                passive, universal);
        }

    }
}
