/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.prove.proveapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.prove.proveapi.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;

public class DataSource {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("address")
    private Optional<? extends String> address;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cipConfidence")
    private Optional<? extends String> cipConfidence;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    private Optional<? extends String> email;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("identifiers")
    private Optional<? extends String> identifiers;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private Optional<? extends String> name;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reasonCodes")
    private Optional<? extends java.util.List<String>> reasonCodes;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("verified")
    private Optional<? extends Boolean> verified;

    @JsonCreator
    public DataSource(
            @JsonProperty("address") Optional<? extends String> address,
            @JsonProperty("cipConfidence") Optional<? extends String> cipConfidence,
            @JsonProperty("email") Optional<? extends String> email,
            @JsonProperty("identifiers") Optional<? extends String> identifiers,
            @JsonProperty("name") Optional<? extends String> name,
            @JsonProperty("reasonCodes") Optional<? extends java.util.List<String>> reasonCodes,
            @JsonProperty("verified") Optional<? extends Boolean> verified) {
        Utils.checkNotNull(address, "address");
        Utils.checkNotNull(cipConfidence, "cipConfidence");
        Utils.checkNotNull(email, "email");
        Utils.checkNotNull(identifiers, "identifiers");
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(reasonCodes, "reasonCodes");
        Utils.checkNotNull(verified, "verified");
        this.address = address;
        this.cipConfidence = cipConfidence;
        this.email = email;
        this.identifiers = identifiers;
        this.name = name;
        this.reasonCodes = reasonCodes;
        this.verified = verified;
    }
    
    public DataSource() {
        this(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> address() {
        return (Optional<String>) address;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> cipConfidence() {
        return (Optional<String>) cipConfidence;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> email() {
        return (Optional<String>) email;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> identifiers() {
        return (Optional<String>) identifiers;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> name() {
        return (Optional<String>) name;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<java.util.List<String>> reasonCodes() {
        return (Optional<java.util.List<String>>) reasonCodes;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Boolean> verified() {
        return (Optional<Boolean>) verified;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public DataSource withAddress(String address) {
        Utils.checkNotNull(address, "address");
        this.address = Optional.ofNullable(address);
        return this;
    }

    public DataSource withAddress(Optional<? extends String> address) {
        Utils.checkNotNull(address, "address");
        this.address = address;
        return this;
    }

    public DataSource withCipConfidence(String cipConfidence) {
        Utils.checkNotNull(cipConfidence, "cipConfidence");
        this.cipConfidence = Optional.ofNullable(cipConfidence);
        return this;
    }

    public DataSource withCipConfidence(Optional<? extends String> cipConfidence) {
        Utils.checkNotNull(cipConfidence, "cipConfidence");
        this.cipConfidence = cipConfidence;
        return this;
    }

    public DataSource withEmail(String email) {
        Utils.checkNotNull(email, "email");
        this.email = Optional.ofNullable(email);
        return this;
    }

    public DataSource withEmail(Optional<? extends String> email) {
        Utils.checkNotNull(email, "email");
        this.email = email;
        return this;
    }

    public DataSource withIdentifiers(String identifiers) {
        Utils.checkNotNull(identifiers, "identifiers");
        this.identifiers = Optional.ofNullable(identifiers);
        return this;
    }

    public DataSource withIdentifiers(Optional<? extends String> identifiers) {
        Utils.checkNotNull(identifiers, "identifiers");
        this.identifiers = identifiers;
        return this;
    }

    public DataSource withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = Optional.ofNullable(name);
        return this;
    }

    public DataSource withName(Optional<? extends String> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    public DataSource withReasonCodes(java.util.List<String> reasonCodes) {
        Utils.checkNotNull(reasonCodes, "reasonCodes");
        this.reasonCodes = Optional.ofNullable(reasonCodes);
        return this;
    }

    public DataSource withReasonCodes(Optional<? extends java.util.List<String>> reasonCodes) {
        Utils.checkNotNull(reasonCodes, "reasonCodes");
        this.reasonCodes = reasonCodes;
        return this;
    }

    public DataSource withVerified(boolean verified) {
        Utils.checkNotNull(verified, "verified");
        this.verified = Optional.ofNullable(verified);
        return this;
    }

    public DataSource withVerified(Optional<? extends Boolean> verified) {
        Utils.checkNotNull(verified, "verified");
        this.verified = verified;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DataSource other = (DataSource) o;
        return 
            java.util.Objects.deepEquals(this.address, other.address) &&
            java.util.Objects.deepEquals(this.cipConfidence, other.cipConfidence) &&
            java.util.Objects.deepEquals(this.email, other.email) &&
            java.util.Objects.deepEquals(this.identifiers, other.identifiers) &&
            java.util.Objects.deepEquals(this.name, other.name) &&
            java.util.Objects.deepEquals(this.reasonCodes, other.reasonCodes) &&
            java.util.Objects.deepEquals(this.verified, other.verified);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            address,
            cipConfidence,
            email,
            identifiers,
            name,
            reasonCodes,
            verified);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DataSource.class,
                "address", address,
                "cipConfidence", cipConfidence,
                "email", email,
                "identifiers", identifiers,
                "name", name,
                "reasonCodes", reasonCodes,
                "verified", verified);
    }
    
    public final static class Builder {
 
        private Optional<? extends String> address = Optional.empty();
 
        private Optional<? extends String> cipConfidence = Optional.empty();
 
        private Optional<? extends String> email = Optional.empty();
 
        private Optional<? extends String> identifiers = Optional.empty();
 
        private Optional<? extends String> name = Optional.empty();
 
        private Optional<? extends java.util.List<String>> reasonCodes = Optional.empty();
 
        private Optional<? extends Boolean> verified = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder address(String address) {
            Utils.checkNotNull(address, "address");
            this.address = Optional.ofNullable(address);
            return this;
        }

        public Builder address(Optional<? extends String> address) {
            Utils.checkNotNull(address, "address");
            this.address = address;
            return this;
        }

        public Builder cipConfidence(String cipConfidence) {
            Utils.checkNotNull(cipConfidence, "cipConfidence");
            this.cipConfidence = Optional.ofNullable(cipConfidence);
            return this;
        }

        public Builder cipConfidence(Optional<? extends String> cipConfidence) {
            Utils.checkNotNull(cipConfidence, "cipConfidence");
            this.cipConfidence = cipConfidence;
            return this;
        }

        public Builder email(String email) {
            Utils.checkNotNull(email, "email");
            this.email = Optional.ofNullable(email);
            return this;
        }

        public Builder email(Optional<? extends String> email) {
            Utils.checkNotNull(email, "email");
            this.email = email;
            return this;
        }

        public Builder identifiers(String identifiers) {
            Utils.checkNotNull(identifiers, "identifiers");
            this.identifiers = Optional.ofNullable(identifiers);
            return this;
        }

        public Builder identifiers(Optional<? extends String> identifiers) {
            Utils.checkNotNull(identifiers, "identifiers");
            this.identifiers = identifiers;
            return this;
        }

        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = Optional.ofNullable(name);
            return this;
        }

        public Builder name(Optional<? extends String> name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }

        public Builder reasonCodes(java.util.List<String> reasonCodes) {
            Utils.checkNotNull(reasonCodes, "reasonCodes");
            this.reasonCodes = Optional.ofNullable(reasonCodes);
            return this;
        }

        public Builder reasonCodes(Optional<? extends java.util.List<String>> reasonCodes) {
            Utils.checkNotNull(reasonCodes, "reasonCodes");
            this.reasonCodes = reasonCodes;
            return this;
        }

        public Builder verified(boolean verified) {
            Utils.checkNotNull(verified, "verified");
            this.verified = Optional.ofNullable(verified);
            return this;
        }

        public Builder verified(Optional<? extends Boolean> verified) {
            Utils.checkNotNull(verified, "verified");
            this.verified = verified;
            return this;
        }
        
        public DataSource build() {
            return new DataSource(
                address,
                cipConfidence,
                email,
                identifiers,
                name,
                reasonCodes,
                verified);
        }
    }
}

