/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.prove.proveapi.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class DataSourceNameResponseInternal {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("firstName")
    private Optional<Long> firstName;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastName")
    private Optional<Long> lastName;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("nameScore")
    private Optional<Long> nameScore;

    @JsonCreator
    public DataSourceNameResponseInternal(
            @JsonProperty("firstName") Optional<Long> firstName,
            @JsonProperty("lastName") Optional<Long> lastName,
            @JsonProperty("nameScore") Optional<Long> nameScore) {
        Utils.checkNotNull(firstName, "firstName");
        Utils.checkNotNull(lastName, "lastName");
        Utils.checkNotNull(nameScore, "nameScore");
        this.firstName = firstName;
        this.lastName = lastName;
        this.nameScore = nameScore;
    }
    
    public DataSourceNameResponseInternal() {
        this(Optional.empty(), Optional.empty(), Optional.empty());
    }

    @JsonIgnore
    public Optional<Long> firstName() {
        return firstName;
    }

    @JsonIgnore
    public Optional<Long> lastName() {
        return lastName;
    }

    @JsonIgnore
    public Optional<Long> nameScore() {
        return nameScore;
    }

    public static Builder builder() {
        return new Builder();
    }


    public DataSourceNameResponseInternal withFirstName(long firstName) {
        Utils.checkNotNull(firstName, "firstName");
        this.firstName = Optional.ofNullable(firstName);
        return this;
    }


    public DataSourceNameResponseInternal withFirstName(Optional<Long> firstName) {
        Utils.checkNotNull(firstName, "firstName");
        this.firstName = firstName;
        return this;
    }

    public DataSourceNameResponseInternal withLastName(long lastName) {
        Utils.checkNotNull(lastName, "lastName");
        this.lastName = Optional.ofNullable(lastName);
        return this;
    }


    public DataSourceNameResponseInternal withLastName(Optional<Long> lastName) {
        Utils.checkNotNull(lastName, "lastName");
        this.lastName = lastName;
        return this;
    }

    public DataSourceNameResponseInternal withNameScore(long nameScore) {
        Utils.checkNotNull(nameScore, "nameScore");
        this.nameScore = Optional.ofNullable(nameScore);
        return this;
    }


    public DataSourceNameResponseInternal withNameScore(Optional<Long> nameScore) {
        Utils.checkNotNull(nameScore, "nameScore");
        this.nameScore = nameScore;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DataSourceNameResponseInternal other = (DataSourceNameResponseInternal) o;
        return 
            Utils.enhancedDeepEquals(this.firstName, other.firstName) &&
            Utils.enhancedDeepEquals(this.lastName, other.lastName) &&
            Utils.enhancedDeepEquals(this.nameScore, other.nameScore);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            firstName, lastName, nameScore);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DataSourceNameResponseInternal.class,
                "firstName", firstName,
                "lastName", lastName,
                "nameScore", nameScore);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<Long> firstName = Optional.empty();

        private Optional<Long> lastName = Optional.empty();

        private Optional<Long> nameScore = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder firstName(long firstName) {
            Utils.checkNotNull(firstName, "firstName");
            this.firstName = Optional.ofNullable(firstName);
            return this;
        }

        public Builder firstName(Optional<Long> firstName) {
            Utils.checkNotNull(firstName, "firstName");
            this.firstName = firstName;
            return this;
        }


        public Builder lastName(long lastName) {
            Utils.checkNotNull(lastName, "lastName");
            this.lastName = Optional.ofNullable(lastName);
            return this;
        }

        public Builder lastName(Optional<Long> lastName) {
            Utils.checkNotNull(lastName, "lastName");
            this.lastName = lastName;
            return this;
        }


        public Builder nameScore(long nameScore) {
            Utils.checkNotNull(nameScore, "nameScore");
            this.nameScore = Optional.ofNullable(nameScore);
            return this;
        }

        public Builder nameScore(Optional<Long> nameScore) {
            Utils.checkNotNull(nameScore, "nameScore");
            this.nameScore = nameScore;
            return this;
        }

        public DataSourceNameResponseInternal build() {

            return new DataSourceNameResponseInternal(
                firstName, lastName, nameScore);
        }

    }
}
