/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.prove.proveapi.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;


public class Identity {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("addresses")
    private Optional<? extends List<Address>> addresses;

    /**
     * Prove’s tiered confidence metric, ranging from -1 to 3, that dynamically adapts to user behavior and
     * various authentication keys. It allows for adaptive security policies, meaning you can require
     * different levels of verification for different types of transactions.
     */
    @JsonProperty("assuranceLevel")
    private String assuranceLevel;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("emails")
    private Optional<? extends List<String>> emails;

    /**
     * The input first name. (required IF verificationType=VerifiedUser)
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("firstName")
    private Optional<String> firstName;

    /**
     * The input last name. (required IF verificationType=VerifiedUser)
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastName")
    private Optional<String> lastName;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("maxAge")
    private Optional<Long> maxAge;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("minAge")
    private Optional<Long> minAge;

    /**
     * Codes explaining the verification outcome
     */
    @JsonProperty("reasons")
    private List<String> reasons;

    @JsonCreator
    public Identity(
            @JsonProperty("addresses") Optional<? extends List<Address>> addresses,
            @JsonProperty("assuranceLevel") String assuranceLevel,
            @JsonProperty("emails") Optional<? extends List<String>> emails,
            @JsonProperty("firstName") Optional<String> firstName,
            @JsonProperty("lastName") Optional<String> lastName,
            @JsonProperty("maxAge") Optional<Long> maxAge,
            @JsonProperty("minAge") Optional<Long> minAge,
            @JsonProperty("reasons") List<String> reasons) {
        Utils.checkNotNull(addresses, "addresses");
        Utils.checkNotNull(assuranceLevel, "assuranceLevel");
        Utils.checkNotNull(emails, "emails");
        Utils.checkNotNull(firstName, "firstName");
        Utils.checkNotNull(lastName, "lastName");
        Utils.checkNotNull(maxAge, "maxAge");
        Utils.checkNotNull(minAge, "minAge");
        Utils.checkNotNull(reasons, "reasons");
        this.addresses = addresses;
        this.assuranceLevel = assuranceLevel;
        this.emails = emails;
        this.firstName = firstName;
        this.lastName = lastName;
        this.maxAge = maxAge;
        this.minAge = minAge;
        this.reasons = reasons;
    }
    
    public Identity(
            String assuranceLevel,
            List<String> reasons) {
        this(Optional.empty(), assuranceLevel, Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), reasons);
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<Address>> addresses() {
        return (Optional<List<Address>>) addresses;
    }

    /**
     * Prove’s tiered confidence metric, ranging from -1 to 3, that dynamically adapts to user behavior and
     * various authentication keys. It allows for adaptive security policies, meaning you can require
     * different levels of verification for different types of transactions.
     */
    @JsonIgnore
    public String assuranceLevel() {
        return assuranceLevel;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> emails() {
        return (Optional<List<String>>) emails;
    }

    /**
     * The input first name. (required IF verificationType=VerifiedUser)
     */
    @JsonIgnore
    public Optional<String> firstName() {
        return firstName;
    }

    /**
     * The input last name. (required IF verificationType=VerifiedUser)
     */
    @JsonIgnore
    public Optional<String> lastName() {
        return lastName;
    }

    @JsonIgnore
    public Optional<Long> maxAge() {
        return maxAge;
    }

    @JsonIgnore
    public Optional<Long> minAge() {
        return minAge;
    }

    /**
     * Codes explaining the verification outcome
     */
    @JsonIgnore
    public List<String> reasons() {
        return reasons;
    }

    public static Builder builder() {
        return new Builder();
    }


    public Identity withAddresses(List<Address> addresses) {
        Utils.checkNotNull(addresses, "addresses");
        this.addresses = Optional.ofNullable(addresses);
        return this;
    }


    public Identity withAddresses(Optional<? extends List<Address>> addresses) {
        Utils.checkNotNull(addresses, "addresses");
        this.addresses = addresses;
        return this;
    }

    /**
     * Prove’s tiered confidence metric, ranging from -1 to 3, that dynamically adapts to user behavior and
     * various authentication keys. It allows for adaptive security policies, meaning you can require
     * different levels of verification for different types of transactions.
     */
    public Identity withAssuranceLevel(String assuranceLevel) {
        Utils.checkNotNull(assuranceLevel, "assuranceLevel");
        this.assuranceLevel = assuranceLevel;
        return this;
    }

    public Identity withEmails(List<String> emails) {
        Utils.checkNotNull(emails, "emails");
        this.emails = Optional.ofNullable(emails);
        return this;
    }


    public Identity withEmails(Optional<? extends List<String>> emails) {
        Utils.checkNotNull(emails, "emails");
        this.emails = emails;
        return this;
    }

    /**
     * The input first name. (required IF verificationType=VerifiedUser)
     */
    public Identity withFirstName(String firstName) {
        Utils.checkNotNull(firstName, "firstName");
        this.firstName = Optional.ofNullable(firstName);
        return this;
    }


    /**
     * The input first name. (required IF verificationType=VerifiedUser)
     */
    public Identity withFirstName(Optional<String> firstName) {
        Utils.checkNotNull(firstName, "firstName");
        this.firstName = firstName;
        return this;
    }

    /**
     * The input last name. (required IF verificationType=VerifiedUser)
     */
    public Identity withLastName(String lastName) {
        Utils.checkNotNull(lastName, "lastName");
        this.lastName = Optional.ofNullable(lastName);
        return this;
    }


    /**
     * The input last name. (required IF verificationType=VerifiedUser)
     */
    public Identity withLastName(Optional<String> lastName) {
        Utils.checkNotNull(lastName, "lastName");
        this.lastName = lastName;
        return this;
    }

    public Identity withMaxAge(long maxAge) {
        Utils.checkNotNull(maxAge, "maxAge");
        this.maxAge = Optional.ofNullable(maxAge);
        return this;
    }


    public Identity withMaxAge(Optional<Long> maxAge) {
        Utils.checkNotNull(maxAge, "maxAge");
        this.maxAge = maxAge;
        return this;
    }

    public Identity withMinAge(long minAge) {
        Utils.checkNotNull(minAge, "minAge");
        this.minAge = Optional.ofNullable(minAge);
        return this;
    }


    public Identity withMinAge(Optional<Long> minAge) {
        Utils.checkNotNull(minAge, "minAge");
        this.minAge = minAge;
        return this;
    }

    /**
     * Codes explaining the verification outcome
     */
    public Identity withReasons(List<String> reasons) {
        Utils.checkNotNull(reasons, "reasons");
        this.reasons = reasons;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Identity other = (Identity) o;
        return 
            Utils.enhancedDeepEquals(this.addresses, other.addresses) &&
            Utils.enhancedDeepEquals(this.assuranceLevel, other.assuranceLevel) &&
            Utils.enhancedDeepEquals(this.emails, other.emails) &&
            Utils.enhancedDeepEquals(this.firstName, other.firstName) &&
            Utils.enhancedDeepEquals(this.lastName, other.lastName) &&
            Utils.enhancedDeepEquals(this.maxAge, other.maxAge) &&
            Utils.enhancedDeepEquals(this.minAge, other.minAge) &&
            Utils.enhancedDeepEquals(this.reasons, other.reasons);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            addresses, assuranceLevel, emails,
            firstName, lastName, maxAge,
            minAge, reasons);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Identity.class,
                "addresses", addresses,
                "assuranceLevel", assuranceLevel,
                "emails", emails,
                "firstName", firstName,
                "lastName", lastName,
                "maxAge", maxAge,
                "minAge", minAge,
                "reasons", reasons);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends List<Address>> addresses = Optional.empty();

        private String assuranceLevel;

        private Optional<? extends List<String>> emails = Optional.empty();

        private Optional<String> firstName = Optional.empty();

        private Optional<String> lastName = Optional.empty();

        private Optional<Long> maxAge = Optional.empty();

        private Optional<Long> minAge = Optional.empty();

        private List<String> reasons;

        private Builder() {
          // force use of static builder() method
        }


        public Builder addresses(List<Address> addresses) {
            Utils.checkNotNull(addresses, "addresses");
            this.addresses = Optional.ofNullable(addresses);
            return this;
        }

        public Builder addresses(Optional<? extends List<Address>> addresses) {
            Utils.checkNotNull(addresses, "addresses");
            this.addresses = addresses;
            return this;
        }


        /**
         * Prove’s tiered confidence metric, ranging from -1 to 3, that dynamically adapts to user behavior and
         * various authentication keys. It allows for adaptive security policies, meaning you can require
         * different levels of verification for different types of transactions.
         */
        public Builder assuranceLevel(String assuranceLevel) {
            Utils.checkNotNull(assuranceLevel, "assuranceLevel");
            this.assuranceLevel = assuranceLevel;
            return this;
        }


        public Builder emails(List<String> emails) {
            Utils.checkNotNull(emails, "emails");
            this.emails = Optional.ofNullable(emails);
            return this;
        }

        public Builder emails(Optional<? extends List<String>> emails) {
            Utils.checkNotNull(emails, "emails");
            this.emails = emails;
            return this;
        }


        /**
         * The input first name. (required IF verificationType=VerifiedUser)
         */
        public Builder firstName(String firstName) {
            Utils.checkNotNull(firstName, "firstName");
            this.firstName = Optional.ofNullable(firstName);
            return this;
        }

        /**
         * The input first name. (required IF verificationType=VerifiedUser)
         */
        public Builder firstName(Optional<String> firstName) {
            Utils.checkNotNull(firstName, "firstName");
            this.firstName = firstName;
            return this;
        }


        /**
         * The input last name. (required IF verificationType=VerifiedUser)
         */
        public Builder lastName(String lastName) {
            Utils.checkNotNull(lastName, "lastName");
            this.lastName = Optional.ofNullable(lastName);
            return this;
        }

        /**
         * The input last name. (required IF verificationType=VerifiedUser)
         */
        public Builder lastName(Optional<String> lastName) {
            Utils.checkNotNull(lastName, "lastName");
            this.lastName = lastName;
            return this;
        }


        public Builder maxAge(long maxAge) {
            Utils.checkNotNull(maxAge, "maxAge");
            this.maxAge = Optional.ofNullable(maxAge);
            return this;
        }

        public Builder maxAge(Optional<Long> maxAge) {
            Utils.checkNotNull(maxAge, "maxAge");
            this.maxAge = maxAge;
            return this;
        }


        public Builder minAge(long minAge) {
            Utils.checkNotNull(minAge, "minAge");
            this.minAge = Optional.ofNullable(minAge);
            return this;
        }

        public Builder minAge(Optional<Long> minAge) {
            Utils.checkNotNull(minAge, "minAge");
            this.minAge = minAge;
            return this;
        }


        /**
         * Codes explaining the verification outcome
         */
        public Builder reasons(List<String> reasons) {
            Utils.checkNotNull(reasons, "reasons");
            this.reasons = reasons;
            return this;
        }

        public Identity build() {

            return new Identity(
                addresses, assuranceLevel, emails,
                firstName, lastName, maxAge,
                minAge, reasons);
        }

    }
}
