/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.prove.proveapi.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class IdentityAttribute {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("attributeType")
    private Optional<String> attributeType;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("attributeValue")
    private Optional<String> attributeValue;

    @JsonCreator
    public IdentityAttribute(
            @JsonProperty("attributeType") Optional<String> attributeType,
            @JsonProperty("attributeValue") Optional<String> attributeValue) {
        Utils.checkNotNull(attributeType, "attributeType");
        Utils.checkNotNull(attributeValue, "attributeValue");
        this.attributeType = attributeType;
        this.attributeValue = attributeValue;
    }
    
    public IdentityAttribute() {
        this(Optional.empty(), Optional.empty());
    }

    @JsonIgnore
    public Optional<String> attributeType() {
        return attributeType;
    }

    @JsonIgnore
    public Optional<String> attributeValue() {
        return attributeValue;
    }

    public static Builder builder() {
        return new Builder();
    }


    public IdentityAttribute withAttributeType(String attributeType) {
        Utils.checkNotNull(attributeType, "attributeType");
        this.attributeType = Optional.ofNullable(attributeType);
        return this;
    }


    public IdentityAttribute withAttributeType(Optional<String> attributeType) {
        Utils.checkNotNull(attributeType, "attributeType");
        this.attributeType = attributeType;
        return this;
    }

    public IdentityAttribute withAttributeValue(String attributeValue) {
        Utils.checkNotNull(attributeValue, "attributeValue");
        this.attributeValue = Optional.ofNullable(attributeValue);
        return this;
    }


    public IdentityAttribute withAttributeValue(Optional<String> attributeValue) {
        Utils.checkNotNull(attributeValue, "attributeValue");
        this.attributeValue = attributeValue;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        IdentityAttribute other = (IdentityAttribute) o;
        return 
            Utils.enhancedDeepEquals(this.attributeType, other.attributeType) &&
            Utils.enhancedDeepEquals(this.attributeValue, other.attributeValue);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            attributeType, attributeValue);
    }
    
    @Override
    public String toString() {
        return Utils.toString(IdentityAttribute.class,
                "attributeType", attributeType,
                "attributeValue", attributeValue);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> attributeType = Optional.empty();

        private Optional<String> attributeValue = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder attributeType(String attributeType) {
            Utils.checkNotNull(attributeType, "attributeType");
            this.attributeType = Optional.ofNullable(attributeType);
            return this;
        }

        public Builder attributeType(Optional<String> attributeType) {
            Utils.checkNotNull(attributeType, "attributeType");
            this.attributeType = attributeType;
            return this;
        }


        public Builder attributeValue(String attributeValue) {
            Utils.checkNotNull(attributeValue, "attributeValue");
            this.attributeValue = Optional.ofNullable(attributeValue);
            return this;
        }

        public Builder attributeValue(Optional<String> attributeValue) {
            Utils.checkNotNull(attributeValue, "attributeValue");
            this.attributeValue = attributeValue;
            return this;
        }

        public IdentityAttribute build() {

            return new IdentityAttribute(
                attributeType, attributeValue);
        }

    }
}
