/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.prove.proveapi.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class RegistrationFiling {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("date")
    private Optional<String> date;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("region")
    private Optional<String> region;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("registrationNumber")
    private Optional<String> registrationNumber;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("registrationType")
    private Optional<String> registrationType;

    @JsonCreator
    public RegistrationFiling(
            @JsonProperty("date") Optional<String> date,
            @JsonProperty("region") Optional<String> region,
            @JsonProperty("registrationNumber") Optional<String> registrationNumber,
            @JsonProperty("registrationType") Optional<String> registrationType) {
        Utils.checkNotNull(date, "date");
        Utils.checkNotNull(region, "region");
        Utils.checkNotNull(registrationNumber, "registrationNumber");
        Utils.checkNotNull(registrationType, "registrationType");
        this.date = date;
        this.region = region;
        this.registrationNumber = registrationNumber;
        this.registrationType = registrationType;
    }
    
    public RegistrationFiling() {
        this(Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty());
    }

    @JsonIgnore
    public Optional<String> date() {
        return date;
    }

    @JsonIgnore
    public Optional<String> region() {
        return region;
    }

    @JsonIgnore
    public Optional<String> registrationNumber() {
        return registrationNumber;
    }

    @JsonIgnore
    public Optional<String> registrationType() {
        return registrationType;
    }

    public static Builder builder() {
        return new Builder();
    }


    public RegistrationFiling withDate(String date) {
        Utils.checkNotNull(date, "date");
        this.date = Optional.ofNullable(date);
        return this;
    }


    public RegistrationFiling withDate(Optional<String> date) {
        Utils.checkNotNull(date, "date");
        this.date = date;
        return this;
    }

    public RegistrationFiling withRegion(String region) {
        Utils.checkNotNull(region, "region");
        this.region = Optional.ofNullable(region);
        return this;
    }


    public RegistrationFiling withRegion(Optional<String> region) {
        Utils.checkNotNull(region, "region");
        this.region = region;
        return this;
    }

    public RegistrationFiling withRegistrationNumber(String registrationNumber) {
        Utils.checkNotNull(registrationNumber, "registrationNumber");
        this.registrationNumber = Optional.ofNullable(registrationNumber);
        return this;
    }


    public RegistrationFiling withRegistrationNumber(Optional<String> registrationNumber) {
        Utils.checkNotNull(registrationNumber, "registrationNumber");
        this.registrationNumber = registrationNumber;
        return this;
    }

    public RegistrationFiling withRegistrationType(String registrationType) {
        Utils.checkNotNull(registrationType, "registrationType");
        this.registrationType = Optional.ofNullable(registrationType);
        return this;
    }


    public RegistrationFiling withRegistrationType(Optional<String> registrationType) {
        Utils.checkNotNull(registrationType, "registrationType");
        this.registrationType = registrationType;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RegistrationFiling other = (RegistrationFiling) o;
        return 
            Utils.enhancedDeepEquals(this.date, other.date) &&
            Utils.enhancedDeepEquals(this.region, other.region) &&
            Utils.enhancedDeepEquals(this.registrationNumber, other.registrationNumber) &&
            Utils.enhancedDeepEquals(this.registrationType, other.registrationType);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            date, region, registrationNumber,
            registrationType);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RegistrationFiling.class,
                "date", date,
                "region", region,
                "registrationNumber", registrationNumber,
                "registrationType", registrationType);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> date = Optional.empty();

        private Optional<String> region = Optional.empty();

        private Optional<String> registrationNumber = Optional.empty();

        private Optional<String> registrationType = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder date(String date) {
            Utils.checkNotNull(date, "date");
            this.date = Optional.ofNullable(date);
            return this;
        }

        public Builder date(Optional<String> date) {
            Utils.checkNotNull(date, "date");
            this.date = date;
            return this;
        }


        public Builder region(String region) {
            Utils.checkNotNull(region, "region");
            this.region = Optional.ofNullable(region);
            return this;
        }

        public Builder region(Optional<String> region) {
            Utils.checkNotNull(region, "region");
            this.region = region;
            return this;
        }


        public Builder registrationNumber(String registrationNumber) {
            Utils.checkNotNull(registrationNumber, "registrationNumber");
            this.registrationNumber = Optional.ofNullable(registrationNumber);
            return this;
        }

        public Builder registrationNumber(Optional<String> registrationNumber) {
            Utils.checkNotNull(registrationNumber, "registrationNumber");
            this.registrationNumber = registrationNumber;
            return this;
        }


        public Builder registrationType(String registrationType) {
            Utils.checkNotNull(registrationType, "registrationType");
            this.registrationType = Optional.ofNullable(registrationType);
            return this;
        }

        public Builder registrationType(Optional<String> registrationType) {
            Utils.checkNotNull(registrationType, "registrationType");
            this.registrationType = registrationType;
            return this;
        }

        public RegistrationFiling build() {

            return new RegistrationFiling(
                date, region, registrationNumber,
                registrationType);
        }

    }
}
