/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


package com.prove.proveapi.models.components;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.prove.proveapi.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

public class V3CompleteResponse {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("idv")
    private Optional<? extends IDVDataInternal> idv;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("kyc")
    private Optional<? extends KYCInternal> kyc;

    /**
     * Next contains the next set of allowed calls in the same flow.
     */
    @JsonProperty("next")
    private Map<String, String> next;

    /**
     * Success returns true if the individual was verified successfully.
     */
    @JsonProperty("success")
    private boolean success;

    @JsonCreator
    public V3CompleteResponse(
            @JsonProperty("idv") Optional<? extends IDVDataInternal> idv,
            @JsonProperty("kyc") Optional<? extends KYCInternal> kyc,
            @JsonProperty("next") Map<String, String> next,
            @JsonProperty("success") boolean success) {
        Utils.checkNotNull(idv, "idv");
        Utils.checkNotNull(kyc, "kyc");
        next = Utils.emptyMapIfNull(next);
        Utils.checkNotNull(success, "success");
        this.idv = idv;
        this.kyc = kyc;
        this.next = next;
        this.success = success;
    }
    
    public V3CompleteResponse(
            Map<String, String> next,
            boolean success) {
        this(Optional.empty(), Optional.empty(), next, success);
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<IDVDataInternal> idv() {
        return (Optional<IDVDataInternal>) idv;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<KYCInternal> kyc() {
        return (Optional<KYCInternal>) kyc;
    }

    /**
     * Next contains the next set of allowed calls in the same flow.
     */
    @JsonIgnore
    public Map<String, String> next() {
        return next;
    }

    /**
     * Success returns true if the individual was verified successfully.
     */
    @JsonIgnore
    public boolean success() {
        return success;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public V3CompleteResponse withIdv(IDVDataInternal idv) {
        Utils.checkNotNull(idv, "idv");
        this.idv = Optional.ofNullable(idv);
        return this;
    }

    public V3CompleteResponse withIdv(Optional<? extends IDVDataInternal> idv) {
        Utils.checkNotNull(idv, "idv");
        this.idv = idv;
        return this;
    }

    public V3CompleteResponse withKyc(KYCInternal kyc) {
        Utils.checkNotNull(kyc, "kyc");
        this.kyc = Optional.ofNullable(kyc);
        return this;
    }

    public V3CompleteResponse withKyc(Optional<? extends KYCInternal> kyc) {
        Utils.checkNotNull(kyc, "kyc");
        this.kyc = kyc;
        return this;
    }

    /**
     * Next contains the next set of allowed calls in the same flow.
     */
    public V3CompleteResponse withNext(Map<String, String> next) {
        Utils.checkNotNull(next, "next");
        this.next = next;
        return this;
    }

    /**
     * Success returns true if the individual was verified successfully.
     */
    public V3CompleteResponse withSuccess(boolean success) {
        Utils.checkNotNull(success, "success");
        this.success = success;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3CompleteResponse other = (V3CompleteResponse) o;
        return 
            Objects.deepEquals(this.idv, other.idv) &&
            Objects.deepEquals(this.kyc, other.kyc) &&
            Objects.deepEquals(this.next, other.next) &&
            Objects.deepEquals(this.success, other.success);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            idv,
            kyc,
            next,
            success);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3CompleteResponse.class,
                "idv", idv,
                "kyc", kyc,
                "next", next,
                "success", success);
    }
    
    public final static class Builder {
 
        private Optional<? extends IDVDataInternal> idv = Optional.empty();
 
        private Optional<? extends KYCInternal> kyc = Optional.empty();
 
        private Map<String, String> next;
 
        private Boolean success;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder idv(IDVDataInternal idv) {
            Utils.checkNotNull(idv, "idv");
            this.idv = Optional.ofNullable(idv);
            return this;
        }

        public Builder idv(Optional<? extends IDVDataInternal> idv) {
            Utils.checkNotNull(idv, "idv");
            this.idv = idv;
            return this;
        }

        public Builder kyc(KYCInternal kyc) {
            Utils.checkNotNull(kyc, "kyc");
            this.kyc = Optional.ofNullable(kyc);
            return this;
        }

        public Builder kyc(Optional<? extends KYCInternal> kyc) {
            Utils.checkNotNull(kyc, "kyc");
            this.kyc = kyc;
            return this;
        }

        /**
         * Next contains the next set of allowed calls in the same flow.
         */
        public Builder next(Map<String, String> next) {
            Utils.checkNotNull(next, "next");
            this.next = next;
            return this;
        }

        /**
         * Success returns true if the individual was verified successfully.
         */
        public Builder success(boolean success) {
            Utils.checkNotNull(success, "success");
            this.success = success;
            return this;
        }
        
        public V3CompleteResponse build() {
            return new V3CompleteResponse(
                idv,
                kyc,
                next,
                success);
        }
    }
}

