/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.prove.proveapi.models.components;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.prove.proveapi.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;


public class V3CompleteIndividualRequest {

    /**
     * Addresses that belong to the individual.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("addresses")
    private Optional<? extends List<V3CompleteAddressEntryRequest>> addresses;

    /**
     * DOB is the date of birth of the individual in one of these formats: YYYY-MM-DD, YYYY-MM, or MM-DD. Acceptable characters are: numeric with symbol '-'.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dob")
    private Optional<String> dob;

    /**
     * Email addresses that belong to the individual.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("emailAddresses")
    private Optional<? extends List<String>> emailAddresses;

    /**
     * First name of the individual.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("firstName")
    private Optional<String> firstName;

    /**
     * Last4SSN is last 4 digits of SSN.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("last4SSN")
    private Optional<String> last4SSN;

    /**
     * Last name of the individual.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastName")
    private Optional<String> lastName;

    /**
     * SSN is the social security number of the individual.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ssn")
    private Optional<String> ssn;

    @JsonCreator
    public V3CompleteIndividualRequest(
            @JsonProperty("addresses") Optional<? extends List<V3CompleteAddressEntryRequest>> addresses,
            @JsonProperty("dob") Optional<String> dob,
            @JsonProperty("emailAddresses") Optional<? extends List<String>> emailAddresses,
            @JsonProperty("firstName") Optional<String> firstName,
            @JsonProperty("last4SSN") Optional<String> last4SSN,
            @JsonProperty("lastName") Optional<String> lastName,
            @JsonProperty("ssn") Optional<String> ssn) {
        Utils.checkNotNull(addresses, "addresses");
        Utils.checkNotNull(dob, "dob");
        Utils.checkNotNull(emailAddresses, "emailAddresses");
        Utils.checkNotNull(firstName, "firstName");
        Utils.checkNotNull(last4SSN, "last4SSN");
        Utils.checkNotNull(lastName, "lastName");
        Utils.checkNotNull(ssn, "ssn");
        this.addresses = addresses;
        this.dob = dob;
        this.emailAddresses = emailAddresses;
        this.firstName = firstName;
        this.last4SSN = last4SSN;
        this.lastName = lastName;
        this.ssn = ssn;
    }
    
    public V3CompleteIndividualRequest() {
        this(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * Addresses that belong to the individual.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<V3CompleteAddressEntryRequest>> addresses() {
        return (Optional<List<V3CompleteAddressEntryRequest>>) addresses;
    }

    /**
     * DOB is the date of birth of the individual in one of these formats: YYYY-MM-DD, YYYY-MM, or MM-DD. Acceptable characters are: numeric with symbol '-'.
     */
    @JsonIgnore
    public Optional<String> dob() {
        return dob;
    }

    /**
     * Email addresses that belong to the individual.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> emailAddresses() {
        return (Optional<List<String>>) emailAddresses;
    }

    /**
     * First name of the individual.
     */
    @JsonIgnore
    public Optional<String> firstName() {
        return firstName;
    }

    /**
     * Last4SSN is last 4 digits of SSN.
     */
    @JsonIgnore
    public Optional<String> last4SSN() {
        return last4SSN;
    }

    /**
     * Last name of the individual.
     */
    @JsonIgnore
    public Optional<String> lastName() {
        return lastName;
    }

    /**
     * SSN is the social security number of the individual.
     */
    @JsonIgnore
    public Optional<String> ssn() {
        return ssn;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Addresses that belong to the individual.
     */
    public V3CompleteIndividualRequest withAddresses(List<V3CompleteAddressEntryRequest> addresses) {
        Utils.checkNotNull(addresses, "addresses");
        this.addresses = Optional.ofNullable(addresses);
        return this;
    }

    /**
     * Addresses that belong to the individual.
     */
    public V3CompleteIndividualRequest withAddresses(Optional<? extends List<V3CompleteAddressEntryRequest>> addresses) {
        Utils.checkNotNull(addresses, "addresses");
        this.addresses = addresses;
        return this;
    }

    /**
     * DOB is the date of birth of the individual in one of these formats: YYYY-MM-DD, YYYY-MM, or MM-DD. Acceptable characters are: numeric with symbol '-'.
     */
    public V3CompleteIndividualRequest withDob(String dob) {
        Utils.checkNotNull(dob, "dob");
        this.dob = Optional.ofNullable(dob);
        return this;
    }

    /**
     * DOB is the date of birth of the individual in one of these formats: YYYY-MM-DD, YYYY-MM, or MM-DD. Acceptable characters are: numeric with symbol '-'.
     */
    public V3CompleteIndividualRequest withDob(Optional<String> dob) {
        Utils.checkNotNull(dob, "dob");
        this.dob = dob;
        return this;
    }

    /**
     * Email addresses that belong to the individual.
     */
    public V3CompleteIndividualRequest withEmailAddresses(List<String> emailAddresses) {
        Utils.checkNotNull(emailAddresses, "emailAddresses");
        this.emailAddresses = Optional.ofNullable(emailAddresses);
        return this;
    }

    /**
     * Email addresses that belong to the individual.
     */
    public V3CompleteIndividualRequest withEmailAddresses(Optional<? extends List<String>> emailAddresses) {
        Utils.checkNotNull(emailAddresses, "emailAddresses");
        this.emailAddresses = emailAddresses;
        return this;
    }

    /**
     * First name of the individual.
     */
    public V3CompleteIndividualRequest withFirstName(String firstName) {
        Utils.checkNotNull(firstName, "firstName");
        this.firstName = Optional.ofNullable(firstName);
        return this;
    }

    /**
     * First name of the individual.
     */
    public V3CompleteIndividualRequest withFirstName(Optional<String> firstName) {
        Utils.checkNotNull(firstName, "firstName");
        this.firstName = firstName;
        return this;
    }

    /**
     * Last4SSN is last 4 digits of SSN.
     */
    public V3CompleteIndividualRequest withLast4SSN(String last4SSN) {
        Utils.checkNotNull(last4SSN, "last4SSN");
        this.last4SSN = Optional.ofNullable(last4SSN);
        return this;
    }

    /**
     * Last4SSN is last 4 digits of SSN.
     */
    public V3CompleteIndividualRequest withLast4SSN(Optional<String> last4SSN) {
        Utils.checkNotNull(last4SSN, "last4SSN");
        this.last4SSN = last4SSN;
        return this;
    }

    /**
     * Last name of the individual.
     */
    public V3CompleteIndividualRequest withLastName(String lastName) {
        Utils.checkNotNull(lastName, "lastName");
        this.lastName = Optional.ofNullable(lastName);
        return this;
    }

    /**
     * Last name of the individual.
     */
    public V3CompleteIndividualRequest withLastName(Optional<String> lastName) {
        Utils.checkNotNull(lastName, "lastName");
        this.lastName = lastName;
        return this;
    }

    /**
     * SSN is the social security number of the individual.
     */
    public V3CompleteIndividualRequest withSsn(String ssn) {
        Utils.checkNotNull(ssn, "ssn");
        this.ssn = Optional.ofNullable(ssn);
        return this;
    }

    /**
     * SSN is the social security number of the individual.
     */
    public V3CompleteIndividualRequest withSsn(Optional<String> ssn) {
        Utils.checkNotNull(ssn, "ssn");
        this.ssn = ssn;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3CompleteIndividualRequest other = (V3CompleteIndividualRequest) o;
        return 
            Objects.deepEquals(this.addresses, other.addresses) &&
            Objects.deepEquals(this.dob, other.dob) &&
            Objects.deepEquals(this.emailAddresses, other.emailAddresses) &&
            Objects.deepEquals(this.firstName, other.firstName) &&
            Objects.deepEquals(this.last4SSN, other.last4SSN) &&
            Objects.deepEquals(this.lastName, other.lastName) &&
            Objects.deepEquals(this.ssn, other.ssn);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            addresses,
            dob,
            emailAddresses,
            firstName,
            last4SSN,
            lastName,
            ssn);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3CompleteIndividualRequest.class,
                "addresses", addresses,
                "dob", dob,
                "emailAddresses", emailAddresses,
                "firstName", firstName,
                "last4SSN", last4SSN,
                "lastName", lastName,
                "ssn", ssn);
    }
    
    public final static class Builder {
 
        private Optional<? extends List<V3CompleteAddressEntryRequest>> addresses = Optional.empty();
 
        private Optional<String> dob = Optional.empty();
 
        private Optional<? extends List<String>> emailAddresses = Optional.empty();
 
        private Optional<String> firstName = Optional.empty();
 
        private Optional<String> last4SSN = Optional.empty();
 
        private Optional<String> lastName = Optional.empty();
 
        private Optional<String> ssn = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Addresses that belong to the individual.
         */
        public Builder addresses(List<V3CompleteAddressEntryRequest> addresses) {
            Utils.checkNotNull(addresses, "addresses");
            this.addresses = Optional.ofNullable(addresses);
            return this;
        }

        /**
         * Addresses that belong to the individual.
         */
        public Builder addresses(Optional<? extends List<V3CompleteAddressEntryRequest>> addresses) {
            Utils.checkNotNull(addresses, "addresses");
            this.addresses = addresses;
            return this;
        }

        /**
         * DOB is the date of birth of the individual in one of these formats: YYYY-MM-DD, YYYY-MM, or MM-DD. Acceptable characters are: numeric with symbol '-'.
         */
        public Builder dob(String dob) {
            Utils.checkNotNull(dob, "dob");
            this.dob = Optional.ofNullable(dob);
            return this;
        }

        /**
         * DOB is the date of birth of the individual in one of these formats: YYYY-MM-DD, YYYY-MM, or MM-DD. Acceptable characters are: numeric with symbol '-'.
         */
        public Builder dob(Optional<String> dob) {
            Utils.checkNotNull(dob, "dob");
            this.dob = dob;
            return this;
        }

        /**
         * Email addresses that belong to the individual.
         */
        public Builder emailAddresses(List<String> emailAddresses) {
            Utils.checkNotNull(emailAddresses, "emailAddresses");
            this.emailAddresses = Optional.ofNullable(emailAddresses);
            return this;
        }

        /**
         * Email addresses that belong to the individual.
         */
        public Builder emailAddresses(Optional<? extends List<String>> emailAddresses) {
            Utils.checkNotNull(emailAddresses, "emailAddresses");
            this.emailAddresses = emailAddresses;
            return this;
        }

        /**
         * First name of the individual.
         */
        public Builder firstName(String firstName) {
            Utils.checkNotNull(firstName, "firstName");
            this.firstName = Optional.ofNullable(firstName);
            return this;
        }

        /**
         * First name of the individual.
         */
        public Builder firstName(Optional<String> firstName) {
            Utils.checkNotNull(firstName, "firstName");
            this.firstName = firstName;
            return this;
        }

        /**
         * Last4SSN is last 4 digits of SSN.
         */
        public Builder last4SSN(String last4SSN) {
            Utils.checkNotNull(last4SSN, "last4SSN");
            this.last4SSN = Optional.ofNullable(last4SSN);
            return this;
        }

        /**
         * Last4SSN is last 4 digits of SSN.
         */
        public Builder last4SSN(Optional<String> last4SSN) {
            Utils.checkNotNull(last4SSN, "last4SSN");
            this.last4SSN = last4SSN;
            return this;
        }

        /**
         * Last name of the individual.
         */
        public Builder lastName(String lastName) {
            Utils.checkNotNull(lastName, "lastName");
            this.lastName = Optional.ofNullable(lastName);
            return this;
        }

        /**
         * Last name of the individual.
         */
        public Builder lastName(Optional<String> lastName) {
            Utils.checkNotNull(lastName, "lastName");
            this.lastName = lastName;
            return this;
        }

        /**
         * SSN is the social security number of the individual.
         */
        public Builder ssn(String ssn) {
            Utils.checkNotNull(ssn, "ssn");
            this.ssn = Optional.ofNullable(ssn);
            return this;
        }

        /**
         * SSN is the social security number of the individual.
         */
        public Builder ssn(Optional<String> ssn) {
            Utils.checkNotNull(ssn, "ssn");
            this.ssn = ssn;
            return this;
        }
        
        public V3CompleteIndividualRequest build() {
            return new V3CompleteIndividualRequest(
                addresses,
                dob,
                emailAddresses,
                firstName,
                last4SSN,
                lastName,
                ssn);
        }
    }
}

