/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.prove.proveapi.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;


public class V3DomainLinkRequest {

    @JsonProperty("pcid")
    private String pcid;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("scopes")
    private Optional<? extends List<String>> scopes;

    @JsonCreator
    public V3DomainLinkRequest(
            @JsonProperty("pcid") String pcid,
            @JsonProperty("scopes") Optional<? extends List<String>> scopes) {
        Utils.checkNotNull(pcid, "pcid");
        Utils.checkNotNull(scopes, "scopes");
        this.pcid = pcid;
        this.scopes = scopes;
    }
    
    public V3DomainLinkRequest(
            String pcid) {
        this(pcid, Optional.empty());
    }

    @JsonIgnore
    public String pcid() {
        return pcid;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> scopes() {
        return (Optional<List<String>>) scopes;
    }

    public static Builder builder() {
        return new Builder();
    }


    public V3DomainLinkRequest withPcid(String pcid) {
        Utils.checkNotNull(pcid, "pcid");
        this.pcid = pcid;
        return this;
    }

    public V3DomainLinkRequest withScopes(List<String> scopes) {
        Utils.checkNotNull(scopes, "scopes");
        this.scopes = Optional.ofNullable(scopes);
        return this;
    }


    public V3DomainLinkRequest withScopes(Optional<? extends List<String>> scopes) {
        Utils.checkNotNull(scopes, "scopes");
        this.scopes = scopes;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3DomainLinkRequest other = (V3DomainLinkRequest) o;
        return 
            Utils.enhancedDeepEquals(this.pcid, other.pcid) &&
            Utils.enhancedDeepEquals(this.scopes, other.scopes);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            pcid, scopes);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3DomainLinkRequest.class,
                "pcid", pcid,
                "scopes", scopes);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String pcid;

        private Optional<? extends List<String>> scopes = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder pcid(String pcid) {
            Utils.checkNotNull(pcid, "pcid");
            this.pcid = pcid;
            return this;
        }


        public Builder scopes(List<String> scopes) {
            Utils.checkNotNull(scopes, "scopes");
            this.scopes = Optional.ofNullable(scopes);
            return this;
        }

        public Builder scopes(Optional<? extends List<String>> scopes) {
            Utils.checkNotNull(scopes, "scopes");
            this.scopes = scopes;
            return this;
        }

        public V3DomainLinkRequest build() {

            return new V3DomainLinkRequest(
                pcid, scopes);
        }

    }
}
