/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.prove.proveapi.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;

/**
 * V3EnrollIdentityResponse
 * 
 * <p>Response body for the V3 Enroll Identity method.
 */
public class V3EnrollIdentityResponse {

    /**
     * A unique Prove-generated identifier for the enrolled identity. This is a UUID that can be used to reference the identity in future requests.
     */
    @JsonProperty("identityId")
    private String identityId;

    /**
     * If true, the request was successful and the identity was created.
     */
    @JsonProperty("success")
    private boolean success;

    @JsonCreator
    public V3EnrollIdentityResponse(
            @JsonProperty("identityId") String identityId,
            @JsonProperty("success") boolean success) {
        Utils.checkNotNull(identityId, "identityId");
        Utils.checkNotNull(success, "success");
        this.identityId = identityId;
        this.success = success;
    }

    /**
     * A unique Prove-generated identifier for the enrolled identity. This is a UUID that can be used to reference the identity in future requests.
     */
    @JsonIgnore
    public String identityId() {
        return identityId;
    }

    /**
     * If true, the request was successful and the identity was created.
     */
    @JsonIgnore
    public boolean success() {
        return success;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * A unique Prove-generated identifier for the enrolled identity. This is a UUID that can be used to reference the identity in future requests.
     */
    public V3EnrollIdentityResponse withIdentityId(String identityId) {
        Utils.checkNotNull(identityId, "identityId");
        this.identityId = identityId;
        return this;
    }

    /**
     * If true, the request was successful and the identity was created.
     */
    public V3EnrollIdentityResponse withSuccess(boolean success) {
        Utils.checkNotNull(success, "success");
        this.success = success;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3EnrollIdentityResponse other = (V3EnrollIdentityResponse) o;
        return 
            Objects.deepEquals(this.identityId, other.identityId) &&
            Objects.deepEquals(this.success, other.success);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            identityId,
            success);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3EnrollIdentityResponse.class,
                "identityId", identityId,
                "success", success);
    }
    
    public final static class Builder {
 
        private String identityId;
 
        private Boolean success;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * A unique Prove-generated identifier for the enrolled identity. This is a UUID that can be used to reference the identity in future requests.
         */
        public Builder identityId(String identityId) {
            Utils.checkNotNull(identityId, "identityId");
            this.identityId = identityId;
            return this;
        }

        /**
         * If true, the request was successful and the identity was created.
         */
        public Builder success(boolean success) {
            Utils.checkNotNull(success, "success");
            this.success = success;
            return this;
        }
        
        public V3EnrollIdentityResponse build() {
            return new V3EnrollIdentityResponse(
                identityId,
                success);
        }
    }
}
