/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.prove.proveapi.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class V3VerifyBatchRequest {
    /**
     * A client-generated unique ID for a specific session. This can be used to identify specific requests.
     * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
     * be accepted.
     * 
     * <p>Do not include Personally Identifiable Information (PII) in this field.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("clientRequestId")
    private Optional<String> clientRequestId;

    /**
     * Batch of verify requests to process. The array length cannot exceed 1000 items.
     */
    @JsonProperty("items")
    private List<VerifyBatchRequestItem> items;

    @JsonCreator
    public V3VerifyBatchRequest(
            @JsonProperty("clientRequestId") Optional<String> clientRequestId,
            @JsonProperty("items") List<VerifyBatchRequestItem> items) {
        Utils.checkNotNull(clientRequestId, "clientRequestId");
        Utils.checkNotNull(items, "items");
        this.clientRequestId = clientRequestId;
        this.items = items;
    }
    
    public V3VerifyBatchRequest(
            List<VerifyBatchRequestItem> items) {
        this(Optional.empty(), items);
    }

    /**
     * A client-generated unique ID for a specific session. This can be used to identify specific requests.
     * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
     * be accepted.
     * 
     * <p>Do not include Personally Identifiable Information (PII) in this field.
     */
    @JsonIgnore
    public Optional<String> clientRequestId() {
        return clientRequestId;
    }

    /**
     * Batch of verify requests to process. The array length cannot exceed 1000 items.
     */
    @JsonIgnore
    public List<VerifyBatchRequestItem> items() {
        return items;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A client-generated unique ID for a specific session. This can be used to identify specific requests.
     * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
     * be accepted.
     * 
     * <p>Do not include Personally Identifiable Information (PII) in this field.
     */
    public V3VerifyBatchRequest withClientRequestId(String clientRequestId) {
        Utils.checkNotNull(clientRequestId, "clientRequestId");
        this.clientRequestId = Optional.ofNullable(clientRequestId);
        return this;
    }


    /**
     * A client-generated unique ID for a specific session. This can be used to identify specific requests.
     * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
     * be accepted.
     * 
     * <p>Do not include Personally Identifiable Information (PII) in this field.
     */
    public V3VerifyBatchRequest withClientRequestId(Optional<String> clientRequestId) {
        Utils.checkNotNull(clientRequestId, "clientRequestId");
        this.clientRequestId = clientRequestId;
        return this;
    }

    /**
     * Batch of verify requests to process. The array length cannot exceed 1000 items.
     */
    public V3VerifyBatchRequest withItems(List<VerifyBatchRequestItem> items) {
        Utils.checkNotNull(items, "items");
        this.items = items;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3VerifyBatchRequest other = (V3VerifyBatchRequest) o;
        return 
            Utils.enhancedDeepEquals(this.clientRequestId, other.clientRequestId) &&
            Utils.enhancedDeepEquals(this.items, other.items);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            clientRequestId, items);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3VerifyBatchRequest.class,
                "clientRequestId", clientRequestId,
                "items", items);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> clientRequestId = Optional.empty();

        private List<VerifyBatchRequestItem> items;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * A client-generated unique ID for a specific session. This can be used to identify specific requests.
         * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
         * be accepted.
         * 
         * <p>Do not include Personally Identifiable Information (PII) in this field.
         */
        public Builder clientRequestId(String clientRequestId) {
            Utils.checkNotNull(clientRequestId, "clientRequestId");
            this.clientRequestId = Optional.ofNullable(clientRequestId);
            return this;
        }

        /**
         * A client-generated unique ID for a specific session. This can be used to identify specific requests.
         * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can
         * be accepted.
         * 
         * <p>Do not include Personally Identifiable Information (PII) in this field.
         */
        public Builder clientRequestId(Optional<String> clientRequestId) {
            Utils.checkNotNull(clientRequestId, "clientRequestId");
            this.clientRequestId = clientRequestId;
            return this;
        }


        /**
         * Batch of verify requests to process. The array length cannot exceed 1000 items.
         */
        public Builder items(List<VerifyBatchRequestItem> items) {
            Utils.checkNotNull(items, "items");
            this.items = items;
            return this;
        }

        public V3VerifyBatchRequest build() {

            return new V3VerifyBatchRequest(
                clientRequestId, items);
        }

    }
}
