/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi;

import com.prove.proveapi.utils.Headers;

/**
 * Prove APIs: This specification describes the Prove API.
 * 
 * <p>OpenAPI Spec - generated.
 */
public class AsyncProveapi {
    private static final Headers _headers = Headers.EMPTY;

    private final AsyncV3 v3;

    private final AsyncDomain domain;

    private final AsyncIdentity identity;

    public AsyncV3 v3() {
        return v3;
    }

    public AsyncDomain domain() {
        return domain;
    }

    public AsyncIdentity identity() {
        return identity;
    }

    private final SDKConfiguration sdkConfiguration;
    private final Proveapi syncSDK;

    AsyncProveapi(Proveapi syncSDK, SDKConfiguration sdkConfiguration) {
        this.syncSDK = syncSDK;
        this.sdkConfiguration = sdkConfiguration;
        this.v3 = new AsyncV3(syncSDK.v3(), sdkConfiguration);
        this.domain = new AsyncDomain(syncSDK.domain(), sdkConfiguration);
        this.identity = new AsyncIdentity(syncSDK.identity(), sdkConfiguration);
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Proveapi sync() {
        return syncSDK;
    }
}
