/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.prove.proveapi;

import static com.prove.proveapi.operations.Operations.AsyncRequestOperation;
import static com.prove.proveapi.operations.Operations.AsyncRequestlessOperation;

import com.prove.proveapi.models.components.V3DomainConfirmLinkRequest;
import com.prove.proveapi.models.components.V3DomainLinkRequest;
import com.prove.proveapi.models.components.V3DomainUnlinkRequest;
import com.prove.proveapi.models.operations.async.V3DomainConfirmLinkRequestRequestBuilder;
import com.prove.proveapi.models.operations.async.V3DomainConfirmLinkRequestResponse;
import com.prove.proveapi.models.operations.async.V3DomainIDRequestRequestBuilder;
import com.prove.proveapi.models.operations.async.V3DomainIDRequestResponse;
import com.prove.proveapi.models.operations.async.V3DomainLinkRequestRequestBuilder;
import com.prove.proveapi.models.operations.async.V3DomainLinkRequestResponse;
import com.prove.proveapi.models.operations.async.V3DomainLinkedRequestRequestBuilder;
import com.prove.proveapi.models.operations.async.V3DomainLinkedRequestResponse;
import com.prove.proveapi.models.operations.async.V3DomainUnlinkRequestRequestBuilder;
import com.prove.proveapi.models.operations.async.V3DomainUnlinkRequestResponse;
import com.prove.proveapi.operations.V3DomainIDRequest;
import com.prove.proveapi.operations.V3DomainLinkedRequest;
import com.prove.proveapi.utils.Headers;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;


public class AsyncDomain {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Domain syncSDK;

    AsyncDomain(Domain syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Domain sync() {
        return syncSDK;
    }


    /**
     * Confirm a domain link request
     * 
     * <p>Confirms a given domain link request by validating the PCID.
     * 
     * @return The async call builder
     */
    public V3DomainConfirmLinkRequestRequestBuilder v3DomainConfirmLinkRequest() {
        return new V3DomainConfirmLinkRequestRequestBuilder(sdkConfiguration);
    }

    /**
     * Confirm a domain link request
     * 
     * <p>Confirms a given domain link request by validating the PCID.
     * 
     * @return {@code CompletableFuture<V3DomainConfirmLinkRequestResponse>} - The async response
     */
    public CompletableFuture<V3DomainConfirmLinkRequestResponse> v3DomainConfirmLinkRequestDirect() {
        return v3DomainConfirmLinkRequest(Optional.empty());
    }

    /**
     * Confirm a domain link request
     * 
     * <p>Confirms a given domain link request by validating the PCID.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<V3DomainConfirmLinkRequestResponse>} - The async response
     */
    public CompletableFuture<V3DomainConfirmLinkRequestResponse> v3DomainConfirmLinkRequest(Optional<? extends V3DomainConfirmLinkRequest> request) {
        AsyncRequestOperation<Optional<? extends V3DomainConfirmLinkRequest>, V3DomainConfirmLinkRequestResponse> operation
              = new com.prove.proveapi.operations.V3DomainConfirmLinkRequest.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get Domain Details
     * 
     * <p>Returns the domain details.
     * 
     * @return The async call builder
     */
    public V3DomainIDRequestRequestBuilder v3DomainIDRequest() {
        return new V3DomainIDRequestRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Domain Details
     * 
     * <p>Returns the domain details.
     * 
     * @return {@code CompletableFuture<V3DomainIDRequestResponse>} - The async response
     */
    public CompletableFuture<V3DomainIDRequestResponse> v3DomainIDRequestDirect() {
        AsyncRequestlessOperation<V3DomainIDRequestResponse> operation
            = new V3DomainIDRequest.Async(sdkConfiguration, _headers);
        return operation.doRequest()
            .thenCompose(operation::handleResponse);
    }


    /**
     * Request a domain link
     * 
     * <p>Create a request to connect the requested domain to the domain the request is made from.
     * 
     * @return The async call builder
     */
    public V3DomainLinkRequestRequestBuilder v3DomainLinkRequest() {
        return new V3DomainLinkRequestRequestBuilder(sdkConfiguration);
    }

    /**
     * Request a domain link
     * 
     * <p>Create a request to connect the requested domain to the domain the request is made from.
     * 
     * @return {@code CompletableFuture<V3DomainLinkRequestResponse>} - The async response
     */
    public CompletableFuture<V3DomainLinkRequestResponse> v3DomainLinkRequestDirect() {
        return v3DomainLinkRequest(Optional.empty());
    }

    /**
     * Request a domain link
     * 
     * <p>Create a request to connect the requested domain to the domain the request is made from.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<V3DomainLinkRequestResponse>} - The async response
     */
    public CompletableFuture<V3DomainLinkRequestResponse> v3DomainLinkRequest(Optional<? extends V3DomainLinkRequest> request) {
        AsyncRequestOperation<Optional<? extends V3DomainLinkRequest>, V3DomainLinkRequestResponse> operation
              = new com.prove.proveapi.operations.V3DomainLinkRequest.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get the list of domains that are linked to this domain.
     * 
     * <p>Returns the accepted and pending links for this domain.
     * 
     * @return The async call builder
     */
    public V3DomainLinkedRequestRequestBuilder v3DomainLinkedRequest() {
        return new V3DomainLinkedRequestRequestBuilder(sdkConfiguration);
    }

    /**
     * Get the list of domains that are linked to this domain.
     * 
     * <p>Returns the accepted and pending links for this domain.
     * 
     * @return {@code CompletableFuture<V3DomainLinkedRequestResponse>} - The async response
     */
    public CompletableFuture<V3DomainLinkedRequestResponse> v3DomainLinkedRequestDirect() {
        AsyncRequestlessOperation<V3DomainLinkedRequestResponse> operation
            = new V3DomainLinkedRequest.Async(sdkConfiguration, _headers);
        return operation.doRequest()
            .thenCompose(operation::handleResponse);
    }


    /**
     * Remove a domain link or request
     * 
     * <p>Remove a domain link or request between the requested domain and the domain the request is made
     * from.
     * 
     * @return The async call builder
     */
    public V3DomainUnlinkRequestRequestBuilder v3DomainUnlinkRequest() {
        return new V3DomainUnlinkRequestRequestBuilder(sdkConfiguration);
    }

    /**
     * Remove a domain link or request
     * 
     * <p>Remove a domain link or request between the requested domain and the domain the request is made
     * from.
     * 
     * @return {@code CompletableFuture<V3DomainUnlinkRequestResponse>} - The async response
     */
    public CompletableFuture<V3DomainUnlinkRequestResponse> v3DomainUnlinkRequestDirect() {
        return v3DomainUnlinkRequest(Optional.empty());
    }

    /**
     * Remove a domain link or request
     * 
     * <p>Remove a domain link or request between the requested domain and the domain the request is made
     * from.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<V3DomainUnlinkRequestResponse>} - The async response
     */
    public CompletableFuture<V3DomainUnlinkRequestResponse> v3DomainUnlinkRequest(Optional<? extends V3DomainUnlinkRequest> request) {
        AsyncRequestOperation<Optional<? extends V3DomainUnlinkRequest>, V3DomainUnlinkRequestResponse> operation
              = new com.prove.proveapi.operations.V3DomainUnlinkRequest.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
